# NumPy

Základní vědecká a analytická knihovna pro vědecké výpočty a manipulaci s daty

- n-rozměrné homogenní pole
- API pro práci s ním
- operace přímo nad poli bez nutnosti iterací
- jednoduché použití

implementace v jazyce C
- efektivnější operace
- vysoký výkon

základ pro mnoho dalších knihoven:
- Pandas: Pro analýzu dat
- SciPy: Pro pokročilé vědecké výpočty
- Matplotlib: Pro vizualizaci dat
- TensorFlow a PyTorch: Pro strojové učení

Instalace

In [ ]:
!python -m pip install numpy

V případě potřeby aktualizace Pip Package Installer

In [ ]:
!python -m pip install --upgrade pip

## Jednoduché datové typy
např. int64, int16, float16, float128, complex128, ap.

In [2]:
import numpy as np
for typ in np.ScalarType: print(typ)

<class 'int'>
<class 'float'>
<class 'complex'>
<class 'bool'>
<class 'bytes'>
<class 'str'>
<class 'memoryview'>
<class 'numpy.bool'>
<class 'numpy.complex64'>
<class 'numpy.complex128'>
<class 'numpy.clongdouble'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.longdouble'>
<class 'numpy.int8'>
<class 'numpy.int16'>
<class 'numpy.intc'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.datetime64'>
<class 'numpy.timedelta64'>
<class 'numpy.object_'>
<class 'numpy.bytes_'>
<class 'numpy.str_'>
<class 'numpy.uint8'>
<class 'numpy.uint16'>
<class 'numpy.uintc'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.void'>


Velikost float v pythonu a numpy

In [2]:
import numpy as np
import sys, math

a = math.sqrt(2)                    # klasická math
print("Math:", a, type(a), sys.getsizeof(a), "B")

print("Numpy:")
b = np.sqrt(2)                      # nebo b = np.double(np.sqrt(2))
print(b, type(b), sys.getsizeof(b), "B")

c = np.longdouble(np.sqrt(2))       # může mít vyšší přesnost, záleží na systému (až 80 b)
print(c, type(c), sys.getsizeof(c), "B")


Math: 1.4142135623730951 <class 'float'> 24 B
Numpy:
1.4142135623730951 <class 'numpy.float64'> 32 B
1.4142135623730951 <class 'numpy.longdouble'> 32 B


Velikost bez režie (přesnost) závisí na HW i OS
- např. Linux na x86-64 s extended precision FPU až 80 bit
- na některých ARM CPU až 128 bit

In [4]:
print("float:     ", np.dtype(float).itemsize)             # 8 B (64 bitů)
print("float64:   ", np.dtype(np.float64).itemsize)        # 8 B (64 bitů)
print("longdouble:", np.dtype(np.longdouble).itemsize)     # Na Windows typicky také 8 B

float:      8
float64:    8
longdouble: 8


V běžných podmínkách se přesnost nezvýší
- např. počítáme součet $n$ floatů

In [8]:
import numpy as np

n = 10**6                       # počet
dx_ld = np.longdouble(1e-18)    # longdouble
dx_f = 1e-18                    # float

sum_f = 0.0
sum_ld = np.longdouble(0)
print("kontrola float:     ", type(dx_f), type(sum_f))
print("kontrola longdouble:", type(dx_ld), type(sum_ld))

for _ in range(n):
    sum_f += dx_f               # float
    sum_ld += dx_ld             # longdouble

print(f"Sum with float:      {sum_f:.50f}")
print(f"Sum with longdouble: {sum_ld:.50f}")


kontrola float:      <class 'float'> <class 'float'>
kontrola longdouble: <class 'numpy.longdouble'> <class 'numpy.longdouble'>
Sum with float:      0.00000000000099999999998890857031569123619914869045
Sum with longdouble: 0.00000000000099999999998890857031569123619914869045


Arbitrární (libovolná) přesnost

In [ ]:
%pip install mpmath

In [26]:
from mpmath import mp
from decimal import Decimal, getcontext
import math

a = math.sqrt(2)                                    # klasická math
print(" "*10, "-.", "-"*15, "x"*34, sep="")
print("math:    ", format(a, ".49f"))               # od 17. des. místa jen šum

# Porovnání s decimal
dva = Decimal('2')
print("dec-math:", format(math.sqrt(dva), ".49f"))  # math.sqrt převádí na float
print(" "*10, "-.", "-"*27, "x"*22, sep="")
print("dec:     ", format(dva.sqrt(), ".49f"))      # nyní vyšší přesnost

getcontext().prec = 50                              # nastavení přesnosti na 50 desetinných míst
print(" "*10, "-.", "-"*49, sep="")
print("dec (50):", format(dva.sqrt(), ".49f"))      # ještě vyšší přesnost
getcontext().prec = 28                              # vrátí se na výchozí hodnotu

print("mp      :", mp.sqrt(2))
mp.dps = 50                                         # přesnost na 50 desetinných míst (decimal places)
print("mp  (50):", mp.sqrt(2))



          -.---------------xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
math:     1.4142135623730951454746218587388284504413604736328
dec-math: 1.4142135623730951454746218587388284504413604736328
          -.---------------------------xxxxxxxxxxxxxxxxxxxxxx
dec:      1.4142135623730950488016887240000000000000000000000
          -.-------------------------------------------------
dec (50): 1.4142135623730950488016887242096980785696718753769
mp      : 1.4142135623730950488016887242096980785696718753769
mp  (50): 1.4142135623730950488016887242096980785696718753769


## Definice polí

Numpy pole 
- pole hodnot
- všechny stejného typu (staticky typovaná, homogenní)
- indexováno n-ticí nezáporných celých čísel

Seznam 
- pythonovský ekvivalent pole
- lze měnit jeho velikost
- může obsahovat prvky různých typů

Výhody NumPy pole
- menší velikost v paměti
- vyšší výkon (optimalizace)
    - výpočty prováděny v kompilovaném jazyce (C/Fortran)
- další implementované funkce (sčítání, násobení, ...)

#### Způsoby vytvoření numpy pole
* z nějakého kontejneru (seznam, n-tice, ...)
* pomocí funkce numpy (arange, linspace, zeros, full, ...)
* načtením ze souboru

In [28]:
import numpy as np
vector = np.array([1, 2, 3, 4])                     # vektor int (ze seznamu)
seznam = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]          # seznam (list)
a1 = np.array(seznam)                               # pole 3 × 3

display(seznam)
display(vector)
display(a1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

array([1, 2, 3, 4])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Srovnání velikostí seznamu a pole

In [29]:
import sys
a1 = np.array(seznam)                           # seznam -> pole
print(a1)
print(seznam)
# velikosti
print("Pole:  ", sys.getsizeof(a1))
print("Seznam:", sys.getsizeof(seznam))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Pole:   200
Seznam: 80


Velikost menší pro větší seznamy

In [30]:
seznam = list(range(100))
a1 = np.array(seznam)
print("Pole:  ", sys.getsizeof(a1))
print("Seznam:", sys.getsizeof(seznam))

Pole:   912
Seznam: 856


#### Vlastnosti pole
- tvar (velikost) pole - **shape** (např. matice 3×3)
- datový typ pole - **dtype** (typ prvků)

Pole celých čísel

In [ ]:
a1 = np.array([             # pole integerů
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])             # pole 3 × 3
print(a1.shape)             # tvar (-> n-tice)
print(a1.size)              # počet prvků
print(sys.getsizeof(a1))    # velikost
a1.dtype                    # typ

(3, 3)
9
200


dtype('int64')

Pole čísel s pohyblivou řádovou čárkou

In [16]:
a1 = np.array([             # pole floatů
    [1, 2, 3.0],
    [4, 5, 6],
    [7, 8, 9]])             # pole 3 × 3
print(a1.shape)             # tvar (-> n-tice)
print(a1.size)              # počet prvků
print(sys.getsizeof(a1))    # velikost
a1.dtype      

(3, 3)
9
200


dtype('float64')

Datový typ můžeme specifikovat už při vytváření pole

In [17]:
matice = np.array([[1, 2], [3, 4]], dtype=complex)
display(matice.dtype)
matice

dtype('complex128')

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Pole větších řádů

In [18]:
krychle = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Shape:", krychle.shape)        # tvar
print("Size: ", krychle.size)         # počet prvků
print("ndim: ", krychle.ndim)         # dimenze
display(krychle)


Shape: (2, 2, 2)
Size:  8
ndim:  3


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Generování jednorozměrného pole

arange(start, stop, step)
- začátek, konec, přírůstek
- pod. jako range()

In [50]:
print(np.array(range(20)))      # standardní iterátor
print(np.arange(20))            # 0 až 19
print(np.arange(4, 20))         # 4 až 19
print(np.arange(4, 20, 2))      # od, do, přírůstek

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 4  6  8 10 12 14 16 18]


Jdou i reálná čísla, ale pozor na chyby

In [ ]:
pole = np.arange(0.0, 20.0, 0.3)
print(pole)
print(pole.size, pole.size*0.3, pole[-1])

[ 0.   0.3  0.6  0.9  1.2  1.5  1.8  2.1  2.4  2.7  3.   3.3  3.6  3.9
  4.2  4.5  4.8  5.1  5.4  5.7  6.   6.3  6.6  6.9  7.2  7.5  7.8  8.1
  8.4  8.7  9.   9.3  9.6  9.9 10.2 10.5 10.8 11.1 11.4 11.7 12.  12.3
 12.6 12.9 13.2 13.5 13.8 14.1 14.4 14.7 15.  15.3 15.6 15.9 16.2 16.5
 16.8 17.1 17.4 17.7 18.  18.3 18.6 18.9 19.2 19.5 19.8]
67 20.099999999999998 19.8


linspace
- pro reálná čísla vhodnější - rovnoměrné dělení
- začátek a konec intervalu plus počet prvků

In [ ]:
np.linspace(0, 20, num=30)

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

logspace
- logaritmická stupnice

In [ ]:
np.logspace(0, 10, 11, base=10)

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07,
       1.e+08, 1.e+09, 1.e+10])

konstantní pole

In [5]:
print(np.zeros(10))
print(np.ones(10, dtype=int))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1 1 1 1]


Pole s náhodnými hodnotami

In [16]:
# několik náhodných čísel z <0, 1) s rovnoměrným rozdělením
display(np.random.random_sample(4))
# matice s náhodnými čísly s normálním rozdělením N(0,1)
np.random.standard_normal((4, 4))

array([0.94264898, 0.96006706, 0.73861373, 0.82566041])

array([[-0.94430219,  0.07601334, -0.25759346, -1.25058601],
       [-0.20167358, -1.15737164,  0.00404463, -0.5619963 ],
       [-0.84663196, -0.02795265, -1.41191899,  0.87355155],
       [ 0.69085723, -2.11470251,  0.96287232, -1.70768584]])

#### Výpis polí
- set_printoptions(precision=n)
- suppress=False/True      &emsp;&emsp;&emsp;&emsp;     # potlačení matematického zápisu

In [24]:
import numpy as np

# Definice pole
vektor = np.array([1.2345678912345, 89.12345, 0.00012345, 1000.5678])

# Výchozí výpis
print("Výchozí výpis:")
print(vektor)

# Nastavení přesnosti
np.set_printoptions(precision=2)  # 2 desetinná místa
print("\nVýpis s přesností na 2 desetinná místa:")
print(vektor)

# Vědecký zápis
np.set_printoptions(precision=4, suppress=False)  # Potlačení vědeckého zápisu vypnuto
print("\nVědecký zápis s přesností na 4 desetinná místa:")
print(vektor)

# Potlačení vědeckého zápisu
np.set_printoptions(suppress=True)
print("\nPotlačení vědeckého zápisu:")
print(vektor)

# Fixní počet míst
np.set_printoptions(precision=8, floatmode="fixed")        # 8 desetinných míst
print("\nFixní počet míst:")
print(vektor)

np.set_printoptions(formatter={'float': lambda x: f"{x:8.3f}"})
print("\nVlastní formátování:")
print(vektor)

np.set_printoptions(precision=12, floatmode="maxprec")  # 2 desetinná místa


Výchozí výpis:
[   1.234567891234   89.12345           0.00012345     1000.5678        ]

Výpis s přesností na 2 desetinná místa:
[   1.23   89.12    0.   1000.57]

Vědecký zápis s přesností na 4 desetinná místa:
[1.2346e+00 8.9123e+01 1.2345e-04 1.0006e+03]

Potlačení vědeckého zápisu:
[   1.2346   89.1235    0.0001 1000.5678]

Fixní počet míst:
[   1.23456789   89.12345000    0.00012345 1000.56780000]

Vlastní formátování:
[   1.235   89.123    0.000 1000.568]


## Základní operace s poli
- probíhá po všech prvcích

In [19]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])    # vytvoření pole 3 × 3
a1                                                  # výpis pole

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Přičtení skalární hodnoty

In [20]:
display(a1 - 1)             # přičtení skaláru
display(-a1)                # změna znamének

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

Násobení skalární hodnotou

In [21]:
display(a1 * 2)             # násobení skalárem
display(a1 / 2)             # dělení skalárem (float)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

Celočíselné dělení

In [22]:
display(a1 // 2)            # celočíselné
display(a1 % 2)             # zbytek

array([[0, 1, 1],
       [2, 2, 3],
       [3, 4, 4]])

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

Použití funkce (vektorové)

In [23]:
np.sin(a1)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

Porovnání

In [24]:
a1 > 3                      # porovnání se skalárem

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

## Operace s více poli
opět po prvcích

definujeme druhé pole

In [25]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])    # pole 3 × 3
a2 = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]])    # pole 3 × 3
a1, a2                  # výpis obou polí

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[0, 1, 0],
        [1, 0, 1],
        [0, 1, 0]]))

Sčítání polí

In [26]:
a1 + a2                 # sčítání po prvcích

array([[1, 3, 3],
       [5, 5, 7],
       [7, 9, 9]])

Násobení (po prvcích)
- neodpovídá maticovému násobení (!)

In [27]:
a1 * a2                 # násobení po prvcích

array([[0, 2, 0],
       [4, 0, 6],
       [0, 8, 0]])

Seznam převeden na pole automaticky

In [28]:
seznam = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]          # seznam (list)
print(seznam)
display(a1 * seznam)            # pole * seznam je pole
a1 + seznam                     # pole + seznam je pole

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

## Indexování, výběr

In [29]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])    # pole 3 × 3
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Pole se chová jako sekvence menších polí
- 1. řádek

In [30]:
a1[0]            # 1. řádek

array([1, 2, 3])

- poslední řádek

In [31]:
a1[-1]           # poslední řádek

array([7, 8, 9])

- rozsah

In [32]:
a1[:-1]          # 1. až předposlední

array([[1, 2, 3],
       [4, 5, 6]])

- prvek

In [33]:
a1[0][1]         # 1. řádek, 2. sloupec

np.int64(2)

- přístup k prvku v NumPy lze i pomocí n-tice

In [34]:
a1[0, 1]         # 1. řádek, 2. sloupec

np.int64(2)

In [35]:
a1[:-1, 1:]      # 1. až předposlední řádek, od 2. sloupce

array([[2, 3],
       [5, 6]])

Výběr řádku a sloupce
- pomocí ":"

In [36]:
display(a1[2])      # 3. řádek
a1[2, :]            # 3. řádek (totéž jako a1[2])

array([7, 8, 9])

array([7, 8, 9])

In [37]:
a1[:, 2]     # 3. sloupec

array([3, 6, 9])

Pozor na editaci!
- jedná se o stejné pole

In [45]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # pole 3 × 3
v = a1[1, :]        # 2. řádek (totéž jako a1[1])
display(v)
v[-1] = 0           # editujeme vektor
a1                  # ovlivní to původní matici

array([4, 5, 6])

array([[1, 2, 3],
       [4, 5, 0],
       [7, 8, 9]])

odkaz na původní objekt, ze kterého bylo pole vytvořeno

In [36]:
display(v.base)         # původní objekt
print(v.base is a1)     # True
print(v.copy().base)    # kopie nemá žádný vztah k pův. objektu

array([[1, 2, 3],
       [4, 5, 0],
       [7, 8, 9]])

True
None


Řezy pomocí indexů

In [37]:
import numpy as np
v = np.array(range(21))         # čísla od 0 do 20
v *= 10                         # [0, 10 ... 200]
print(v)
indexy = [1,3,10]
v[indexy]                       # neboli v[[1,3,10]]

[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180 190 200]


array([ 10,  30, 100])

Výběr prvků pomocí pole logických hodnot

In [54]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # pole 3 × 3
display(a1)
vetsi = a1 > 4          # vpravo matice, obsahuje True a False
display(vetsi)          # pole logických hodnot
a1[vetsi]               # pole prvků (jednorozměrné)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

array([5, 6, 7, 8, 9])

In [62]:
y1 = np.sin(a1)
mask = (a1 >= 5) & (a1 <= 7)
print("a1:\n", a1)
print("y1:\n", y1)
print("mask:\n", mask)
x_subset = a1[mask]
y_subset = y1[mask]
display(x_subset)
display(y_subset)

a1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
y1:
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
mask:
 [[False False False]
 [False  True  True]
 [ True False False]]


array([5, 6, 7])

array([-0.95892427, -0.2794155 ,  0.6569866 ])

Logické spojení operací přes bitové operátory "&" (*a*) a "|" (*nebo*)
- neintuitivní priorita - <font color="red">nutno závorkovat!</font>
- (Python neumožňuje předefinovat chování operátorů and a or)

In [41]:
(a1 > 3) & (a1 < 7)

array([[False, False, False],
       [ True,  True, False],
       [False, False, False]])

#### Změna pořadí řádků a sloupců, kopie řádků a sloupců

In [46]:
display(a1[1])          # 2. řádek
display(a1[[1]])        # pole obsahující 2. řádek
a1[[0, 2, 1, 1]]        # řádky 0, 2, 1 a 1 (pole obsahující tyto řádky)

array([4, 5, 0])

array([[4, 5, 0]])

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 0],
       [4, 5, 0]])

In [43]:
a1[:, [2, 2, 0, 0]]      # sloupce 2, 2, 0, 0

array([[3, 3, 1, 1],
       [0, 0, 4, 4],
       [9, 9, 7, 7]])

## Operace s různě velkými poli
- odpovídající dimenze se "rozšíří" (jako u skaláru) - broadcasting

Přičtení vektoru

In [78]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # pole 3 × 3
b = np.array([1, 0, 10])        # velikost 3 (stejná jako matice a1)
display(a1)
display(b)
print("Broadcasting (vektor přičten ke každému řádku):")
display(a1 + b)                 # přičtení vektoru ke všem řádkům
#display(a1 + b[:,np.newaxis])  # kdybychom chtěli přičíst ke sloupcům

c = np.array([1, 0])            # (jiné velikosti) - chyba
print("Velikost vektoru musí být roven počtu sloupců")
b + c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([ 1,  0, 10])

Broadcasting (vektor přičten ke každému řádku):


array([[ 2,  2, 13],
       [ 5,  5, 16],
       [ 8,  8, 19]])

Velikost vektoru musí být roven počtu sloupců


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [79]:
print("Původní:\n", a1)
print("Přičtení řádkového vektoru:\n",   a1 + [1, 0, 10])       # přičteno k řádkům
print("Násobení řádkovým vektorem:\n",   a1 * [1, 0, 10])       # vynásobeny řádky
print("Násobení sloupcovým vektorem:\n", a1 * [[1], [0], [10]]) # vynásobeny sloupce

Původní:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Přičtení řádkového vektoru:
 [[ 2  2 13]
 [ 5  5 16]
 [ 8  8 19]]
Násobení řádkovým vektorem:
 [[ 1  0 30]
 [ 4  0 60]
 [ 7  0 90]]
Násobení sloupcovým vektorem:
 [[ 1  2  3]
 [ 0  0  0]
 [70 80 90]]


## Editace polí

In [80]:
a1[0, 0] = 100               # jedna z možností
a1[1][1] = 200               # jiný způsob
a1

array([[100,   2,   3],
       [  4, 200,   6],
       [  7,   8,   9]])

lze měnit jakýkoliv výběr, funguje rozšiřování (broadcasting)

In [81]:
a1[0] = 100          # první řádek
print(a1)
a1[:, 1] = 500       # druhý sloupec
print(a1)
a1[:] = 100          # všechny prvky
a1

[[100 100 100]
 [  4 200   6]
 [  7   8   9]]
[[100 500 100]
 [  4 500   6]
 [  7 500   9]]


array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

Editace rozšířeným přiřazením

In [82]:
a1 *= 2
a1

array([[200, 200, 200],
       [200, 200, 200],
       [200, 200, 200]])

Operace array = array * 2 dává stejný výsledek, ale vytvoří nové pole, které pak přiřadí do původní proměnné

## Tvoření matic pomocí funkcí

Naplnění matice m × n libovolným stejným číslem

In [83]:
np.full((4, 4), 3.14)                    # tvar, hodnota

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

Naplnění matice m × n nulami (jedničkami)

In [ ]:
np.zeros((4, 4)), np.ones((4, 4))     # nuly, jedničky

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

Jednotková a diagonální matice (vždy čtvercové)

In [ ]:
display(np.eye(4))                  # v argumentu dimenze
display(np.diag([1, 2, 3, 4]))      # prvky diagonály
np.diagonal(np.diag([9,8,7]))       # vrátí diagonálu jako vektor

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

array([9, 8, 7])

Vždy lze specifikovat datový typ

In [ ]:
int_zeros = np.zeros((4, 4), dtype='int8')
print(int_zeros.dtype)
int_zeros

int8


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

## Změna tvaru pole

In [ ]:
a1 = np.arange(12)            # výchozí pole
display(a1)
display(a1.shape)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

(12,)

reshape
- musí odpovídat velikost

In [ ]:
a2 = a1.reshape((3, 4))         # řádky, sloupce
a3 = a1.reshape((4, 3))
a2, a3

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

- nahradíme-li jedno z čísel -1, dopočítá se 

In [ ]:
a2 = a1.reshape((-1, 4))         # řádky, sloupce
a3 = a1.reshape((4, 3))
a3 = a1.reshape((-1, 3))
a2, a3

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [104]:
C = np.arange(2).reshape(-1,1)   # sloupec 0,1
R = np.arange(2).reshape(1,-1)   # řádek 0,1
print("Sloupcový vektor:    rozměry", C.shape)
display(C)
print("Řádkový vektor:      rozměry", R.shape)
display(R)
print("Součet (využívá se broadcastiug):")
C + R                               # broadcasting

Sloupcový vektor:    rozměry (2, 1)


array([[0],
       [1]])

Řádkový vektor:      rozměry (1, 2)


array([[0, 1]])

Součet (využívá se broadcastiug):


array([[0, 1],
       [1, 2]])

Pozor na editaci!
- jedná se o stejné pole

In [109]:
a1 = np.arange(12)          # výchozí pole
a2 = a1.reshape((3, 4))     # řádky, sloupce
a3 = a1.reshape((4, 3))

a2[2,2] = 100               # 3. řádek, 3. sloupec (pův. 10)
a2, a1, a3                  # editovalo se jen a2

(array([[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9, 100,  11]]),
 array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100,  11]),
 array([[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9, 100,  11]]))

Pro kopii dat copy

In [111]:
a2 = a1.reshape((3, 4)).copy()
a2[2, 2] = 10
a2, a3

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9, 100,  11]]))

Transpozice

In [114]:
a2, a2.T

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]))

In [116]:
v = np.array([1,3,7])
display(v)
display(v.T)        # transpozice vektoru je v numpy stejný vektor
v == v.T

array([1, 3, 7])

array([1, 3, 7])

array([ True,  True,  True])

Přidání další osy pomocí newaxis
- rozšíření rozměrů pole o jednu novou osu

1D pole → 2D pole

In [153]:
import numpy as np
v = np.array([1, 2, 3])             # Původní pole (1D)
print(v, "  rozměry", v.shape)

# Přidání nové osy, čímž vytvoříme 2D pole
v2a = v[np.newaxis, :]              # zmena 1D pole na řádkový vektor (2D)
print(v2a, "rozměry", v2a.shape)
v2b = v[None, :]                    # jiný způsob, ekvivalentní
print(v2b, "rozměry", v2b.shape)

# Přidání nové osy, čímž vytvoříme 2D pole
v2c = v[:, np.newaxis]             # zmena 1D pole na sloupcový vektor (2D)
print(v2c, "    rozměry", v2c.shape)

[1 2 3]   rozměry (3,)
[[1 2 3]] rozměry (1, 3)
[[1 2 3]] rozměry (1, 3)
[[1]
 [2]
 [3]]     rozměry (3, 1)


2D pole → 3D pole

In [ ]:
b = np.array([[1, 2, 3],        # 2D array, tvar (2,3)
              [4, 5, 6]])
print(b.shape)                  # (2,3)

# Přidání nové osy mezi 2. a 3. dimenzi → výsledné pole je 3D (2,1,3)
b_expanded = b[:, np.newaxis, :]
print(b_expanded.shape)         # (2,1,3)
print(b_expanded)


(2, 3)
(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]


In [160]:
a2d = np.array([[1, 2, 3],          # Původní 2D pole (3x3)
                [4, 5, 6],
                [7, 8, 9]])
a3d = a2d[:, :, np.newaxis]         # Přidání nové osy do druhé dimenze, čímž vytvoříme 3D pole
print(a3d.shape)                    # Výstup: (3, 3, 1)
display(a3d)

a3d = a2d[:, np.newaxis, :]         # Přidání nové osy do druhé dimenze, čímž vytvoříme 3D pole
print(a3d.shape)                    # Výstup: (3, 1, 3)
display(a3d)

a3d = a2d[np.newaxis, :, :]         # Přidání nové osy do druhé dimenze, čímž vytvoříme 3D pole
print(a3d.shape)                    # Výstup: (1, 3, 3)
display(a3d)


(3, 3, 1)


array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

(3, 1, 3)


array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

(1, 3, 3)


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [167]:
x = np.array([1, 2, 3])             # (3,)
y = np.array([[10, 20, 30],         # (2,3)
              [40, 50, 60],
              [70, 80, 90]])
print(x+y)
print(x[np.newaxis, :])
print(x[:, np.newaxis])

# Chceme sečíst x ke každému sloupci y
result = y + x[:,np.newaxis]
print(result)


[[11 22 33]
 [41 52 63]
 [71 82 93]]
[[1 2 3]]
[[1]
 [2]
 [3]]
[[11 21 31]
 [42 52 62]
 [73 83 93]]


#### Skládání polí - stacking (concatenate)

In [168]:
arr1 = np.arange(1,10).reshape(3,3)     # příprava matic
arr2 = 2*arr1
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Horizontální skládání (vedle sebe)

In [169]:
arr3=np.hstack((arr1, arr2))        # horizontální skládání
#arr3=np.concatenate((arr1, arr2), axis=1)
arr3

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

Verikální skládání (nad sebe)

In [170]:
arr3=np.vstack((arr1, arr2))        # vertikální skládání
#arr3=np.concatenate((arr1, arr2), axis=0)
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

Složení přes třetí osu

In [171]:
print(arr1)
print(arr2)

arr3=np.dstack((arr1, arr2))    # složení přes osu z (depth)
display(arr3)                   # dimenze 3, vnitřní vektor 1. složka arr1, 2. složka arr2

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])

Pro 1D pole můžeme použít funkce column_stack (obdoba hstack) a row_stack (=vstack)

In [178]:
arr1 = np.arange(4,7) 
arr2 = 2 * arr1
print(arr1)
print(arr2)

# column stack
print("\nColumn stack")
print(np.column_stack((arr1,arr2)))
print(np.hstack((arr1.T,arr2.T)))       # transpozice nemá vliv na 1D pole

# row stack
print("\nRow stack")
print(np.row_stack((arr1,arr2)))        # zastaralé
print(np.vstack((arr1,arr2)))


[4 5 6]
[ 8 10 12]

Column stack
[[ 4  8]
 [ 5 10]
 [ 6 12]]
[ 4  5  6  8 10 12]

Row stack
[[ 4  5  6]
 [ 8 10 12]]
[[ 4  5  6]
 [ 8 10 12]]


C:\Users\P\AppData\Local\Temp\ipykernel_16776\1585177699.py:13: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((arr1,arr2)))        # zastaralé


Dělení matice (opačný proces): split 
- hsplit - pole sloupců
- vsplit - pole řádků

Dělení na sloupce (hsplit)

In [180]:
arr=np.arange(1,10).reshape(3,3)
print(arr)

# vodorovné dělení (na sloupce)
print("\nSeznam sloupců:")
np.hsplit(arr, 3)    # nebo np.split(arr,3,axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Seznam sloupců:


[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

Dělení na řádky (vsplit)

In [181]:
# svislé dělení (na řádky)
np.vsplit(arr, 3)    # nebo np.split(arr,3,axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

## Datové typy polí

Možnost definovat typ při vytvoření

In [ ]:
print(np.zeros(4, dtype=int))        # pro matici (4,4)
print(np.zeros(4, dtype=float))
print(np.zeros(4, dtype=bool))

[0 0 0 0]
[0. 0. 0. 0.]
[False False False False]


Změna datového typu

In [ ]:
arr=np.arange(1,10).reshape(3,3)
print(arr)

arr=arr.astype(float)
print(arr)
print("Změněný typ:", arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Změněný typ: float64


Pokud uložíme různé datové typy, výsledkem je defaultně string 

In [3]:
np.array([0, 3.14, "ahoj"])     # dtype='<U32' little-endian 32 character string

array(['0', '3.14', 'ahoj'], dtype='<U32')

Nejobecnější typ je object

In [ ]:
np.array([0, 3.14, "ahoj"], dtype=object)

array([0, 3.14, 'ahoj'], dtype=object)

Další možnosti: Klasické řetězcové specifikace, bytestring (ukončeny \0), složené datové typy (records)

## Informace o hodnotách polí

In [ ]:
E = np.eye(3)
if E.any():                         # obsahuje cokoliv nenulového
    print('Alespoň jeden prvek je nenulový')
if E.all():                         # všechny prvky nenulové
    print('Všechny prvky jsou nenulové')
print(E.size)
if E.size:                          # počet prvků
    print('Pole obsahuje nějaké prvky')

Alespoň jeden prvek je nenulový
9
Pole obsahuje nějaké prvky


## Iterace

In [2]:
import numpy as np
v = np.array([1, 2, 3, 4])

for element in v:
    print(element)

1
2
3
4


Iteruje se přes první index (po řádcích)

In [10]:
M = np.array([[1, 2], [3, 4]])

for row in M:
    print(f"řádek: {row}")

řádek: [1 2]
řádek: [3 4]


Přístup k indexům přes enumerate
- vrací index a hodnotu každého prvku

In [33]:
v = np.array([1, 2, 3, 4])
for i, p in enumerate(v):
    print(f"prvek č. {i}: {p}")

prvek č. 0: 1
prvek č. 1: 2
prvek č. 2: 3
prvek č. 3: 4


In [35]:
M = np.array([[1, 2], [3, 4]])

for row_idx, row in enumerate(M):
    print(f"řádek č. {row_idx}: {row}")
    
    for col_idx, element in enumerate(row):
        print(f"  prvek {element} ve sloupci {col_idx}")
       
        # update the matrix M: square each element
        M[row_idx, col_idx] = element ** 2
M

řádek č. 0: [1 2]
  prvek 1 ve sloupci 0
  prvek 2 ve sloupci 1
řádek č. 1: [3 4]
  prvek 3 ve sloupci 0
  prvek 4 ve sloupci 1


array([[ 1,  4],
       [ 9, 16]])

## Vektorové funkce
např. vytvoříme hodnoty z intervalu 0 až $\pi$ s dělením na 1000 dílků a spočítáme sinus 

In [ ]:
#                od,   do,   dělení   
a1 = np.linspace(0, np.pi, num=1000)    # vytvoření pole
a1[:10]                                 # výpis prvních 10 prvků

array([0.        , 0.00314474, 0.00628947, 0.00943421, 0.01257895,
       0.01572369, 0.01886842, 0.02201316, 0.0251579 , 0.02830264])

In [ ]:
sinus = np.sin(a1)                      # použití funkce sin
sinus[:10]                              # výpis prvních 10 prvků

array([0.        , 0.00314473, 0.00628943, 0.00943407, 0.01257862,
       0.01572304, 0.0188673 , 0.02201138, 0.02515525, 0.02829886])

### Vektorizace funkcí
požadujeme, aby argumentem i výsledkem funkce byl vektor

In [2]:
def Theta(x):
    """
    Scalar implemenation of the Heaviside step function.
    """
    if x >= 0:
        return 1
    else:
        return 0

In [ ]:
# toto bychom chtěli, ale nebude fungovat
Theta(np.array([-3, -2, -1, 0, 1, 2, 3]))

In [4]:
import numpy as np
Theta_vec = np.vectorize(Theta)
Theta_vec(np.array([-3, -2, -1, 0, 1, 2, 3]))

array([0, 0, 0, 1, 1, 1, 1])

Vhodnější vektorová funkce

In [5]:
def Theta_numpy(x):
    """
    Vector-aware implemenation of the Heaviside step function.
    """
    return 1 * (x >= 0)

In [6]:
Theta_numpy(np.array([-3, -2, -1, 0, 1, 2, 3]))

array([0, 0, 0, 1, 1, 1, 1])

Porovnání rychlosti pomocí magického příkazu %timeit

In [7]:
randvec = np.random.random_sample((10000)) * 2000 - 1000
%timeit Theta_vec(randvec)
%timeit Theta_numpy(randvec)

1.89 ms ± 171 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
21.4 µs ± 378 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# Lineární algebra s np.linalg
Základní operace, doplněno v SciPy


### Maticové násobení
- původně funkce dot, od Pythonu 3.5 operátor @ (mATrix multiplication),

Násobení matice vektorem

In [6]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([1, 0, 0])
a1 @ vector, np.dot(a1, vector), a1.dot(vector)

(array([1, 4, 7]), array([1, 4, 7]), array([1, 4, 7]))

Násobení dvou matic

In [7]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2 = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]])
a1 @ a2, np.dot(a1, a2), a1.dot(a2)

(array([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]]),
 array([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]]),
 array([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]]))

Neodpovídající rozměry

In [8]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([1, 0, 0])
vector @ a1                         # automatická transpozice

array([1, 2, 3])

In [9]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([1, 0])            # pouze 2 hodnoty - chyba
vector @ a1

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

Výpočet determinantu

In [48]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

np.float64(-2.0000000000000004)

Výpočet hodnosti matice

In [49]:
from numpy.linalg import matrix_rank
print(a)
print("Hodnost a:", matrix_rank(a))
print("Hodnost jednotkové 4x4:", matrix_rank(np.eye(4)))

[[1 2]
 [3 4]]
Hodnost a: 2
Hodnost jednotkové 4x4: 4


In [50]:
I=np.eye(4)
I[-1,-1] = 0                # odstraníme poslední diag. hodnotu
matrix_rank(I)              # hodnost je menší

np.int64(3)

Stopa matice

In [51]:
np.trace(np.eye(3))   # součet prvků na diagonále

np.float64(3.0)

In [52]:
a = np.arange(8).reshape((2,2,2))        # 2×2×2
print(a)
np.trace(a)                              # 2 diagonály: 0+6, 1+7

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([6, 8])

Inverze matice

In [53]:
from numpy.linalg import inv
a = np.array([[1., 2.], [3., 4.]])
ainv = inv(a)           # inverzní
print(a)
print(ainv)
print(a @ ainv)         # kontrola
np.allclose(a @ ainv, np.eye(2))

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


True

## Třída Matice
pohodlné, ale nepřináší nic nového

In [9]:
import numpy as np
A1 = np.array([1, 2, 3, 4]).reshape(2, 2)   # array
display(A1)

A = np.matrix('[1 2;3 4]')                # matrix (pův. np.mat)
A

array([[1, 2],
       [3, 4]])

matrix([[1, 2],
        [3, 4]])

Způsoby vytvoření

In [10]:
B = np.matrix(A1)
C = np.matrix([[1, 2],[3, 4]])
D = np.matrix("1 2; 3, 4")
E = np.matrix("[1 2; 3, 4]")
F = np.asmatrix("[1 2; 3, 4]")
B, C, D, E, F

(matrix([[1, 2],
         [3, 4]]),
 matrix([[1, 2],
         [3, 4]]),
 matrix([[1, 2],
         [3, 4]]),
 matrix([[1, 2],
         [3, 4]]),
 matrix([[1, 2],
         [3, 4]]))

Transpozice, inverze

In [11]:
print("--- Array: ----")
display(A1.T, np.linalg.inv(A1))            # array
print("\n---- Matrix: ----")
display(A.T, A.I)                           # matrix

--- Array: ----


array([[1, 3],
       [2, 4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])


---- Matrix: ----


matrix([[1, 3],
        [2, 4]])

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

Násobení matic a vektorů

In [46]:
# operace s poli
A = np.array([[1, 2],[3, 4]])           # matice jako pole
b = np.array([5, 6])                    # vektor jako pole

print("Arrays:")
print(A, "(matice A)")
print(b, "  (vektor b)")

print("\nb * A,  A * b  (násobení po prvcích + broadcasting):")
print(b*A)                            # násobení vektorem zleva
print(A*b.T)                          # nebo display(A*b)
print("\nb @ A, A @ b  (maticové násobení):")
display(b@A)
A@b.T

Arrays:
[[1 2]
 [3 4]] (matice A)
[5 6]   (vektor b)

b * A,  A * b  (násobení po prvcích + broadcasting):
[[ 5 12]
 [15 24]]
[[ 5 12]
 [15 24]]

b @ A, A @ b  (maticové násobení):


array([23, 34])

array([17, 39])

Operace s maticemi

In [43]:
# operace s maticemi
A = np.matrix('[1 2;3 4]')              # matice
b = np.matrix('[5 6]')                  # vektor jako matice
print("Matrices:")
display(b*A)
display(A*b.T)
display(b@A)
A@b.T
# operátory * a @ jsou rovnocenné

Matrices:


matrix([[23, 34]])

matrix([[17],
        [39]])

matrix([[23, 34]])

matrix([[17],
        [39]])

## Práce se soubory
Nejdříve vytvoříme textový soubor s daty
- writefile (file) - magický příkaz, vytvoří soubor a zapíše do něj to, co následuje

In [ ]:
%%writefile tmp/ascii_data_1.txt         
 1    -6.1    -6.1    -6.1 1
 2   -15.4   -15.4   -15.4 1
 3   -15.0   -15.0   -15.0 1
 4   -19.3   -19.3   -19.3 1
 5   -16.8   -16.8   -16.8 1
 6   -11.4   -11.4   -11.4 1
 7    -7.6    -7.6    -7.6 1
 8    -7.1    -7.1    -7.1 1
 9   -10.1   -10.1   -10.1 1
10    -9.5    -9.5    -9.5 1

Writing tmp/ascii_data_1.txt


Pokusíme se načíst data ze souboru

In [ ]:
data1 = np.genfromtxt('tmp/ascii_data_1.txt')
data2 = np.loadtxt('tmp/ascii_data_1.txt')
#print(data1 == data2)
data1, data2

(array([[  1. ,  -6.1,  -6.1,  -6.1,   1. ],
        [  2. , -15.4, -15.4, -15.4,   1. ],
        [  3. , -15. , -15. , -15. ,   1. ],
        [  4. , -19.3, -19.3, -19.3,   1. ],
        [  5. , -16.8, -16.8, -16.8,   1. ],
        [  6. , -11.4, -11.4, -11.4,   1. ],
        [  7. ,  -7.6,  -7.6,  -7.6,   1. ],
        [  8. ,  -7.1,  -7.1,  -7.1,   1. ],
        [  9. , -10.1, -10.1, -10.1,   1. ],
        [ 10. ,  -9.5,  -9.5,  -9.5,   1. ]]),
 array([[  1. ,  -6.1,  -6.1,  -6.1,   1. ],
        [  2. , -15.4, -15.4, -15.4,   1. ],
        [  3. , -15. , -15. , -15. ,   1. ],
        [  4. , -19.3, -19.3, -19.3,   1. ],
        [  5. , -16.8, -16.8, -16.8,   1. ],
        [  6. , -11.4, -11.4, -11.4,   1. ],
        [  7. ,  -7.6,  -7.6,  -7.6,   1. ],
        [  8. ,  -7.1,  -7.1,  -7.1,   1. ],
        [  9. , -10.1, -10.1, -10.1,   1. ],
        [ 10. ,  -9.5,  -9.5,  -9.5,   1. ]]))

Opětovné uložení

In [ ]:
np.savetxt("tmp/ascii_data_1_new.txt", data1, fmt="%6g")     # uložíme pod jiným jménem
print(open("tmp/ascii_data_1_new.txt", "r").read())             # přesvědčíme se

     1   -6.1   -6.1   -6.1      1
     2  -15.4  -15.4  -15.4      1
     3    -15    -15    -15      1
     4  -19.3  -19.3  -19.3      1
     5  -16.8  -16.8  -16.8      1
     6  -11.4  -11.4  -11.4      1
     7   -7.6   -7.6   -7.6      1
     8   -7.1   -7.1   -7.1      1
     9  -10.1  -10.1  -10.1      1
    10   -9.5   -9.5   -9.5      1



Je možné používat i vlastní NumPy formát, příkazy jsou stejné bez txt (save, load)

# Cvičení: Srovnání rychlosti

#### Součet vektorů

In [ ]:
import time
import numpy as np

velikostVektoru = 1000000

def SoucetSeznamy1():                   # klasické for
    t1 = time.time()
    X = range(velikostVektoru)
    Y = range(velikostVektoru)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1

def SoucetSeznamy():
    t1 = time.time()
    X = range(velikostVektoru)
    Y = range(velikostVektoru)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - t1

def SoucetNumPy():                      # numpy
    t1 = time.time()
    X = np.arange(velikostVektoru)
    Y = np.arange(velikostVektoru)
    Z = X + Y
    return time.time() - t1

print(SoucetSeznamy1())
t1 = SoucetSeznamy()
t2 = SoucetNumPy()
print(t1)
print(t2)
if t2 != 0:
    print("Numpy je rychlejší {:.2f}×".format(t1/t2))
else:
    print("Podíl nelze stanovit")

0.3661055564880371
0.28478312492370605
0.004105329513549805
Numpy je rychlejší 69.37×


#### Násobení vektorů

Klasicky (bez NumPy)

In [ ]:
from time import process_time
mez = 100000                        # velikost vektoru
opak = 100                          # počet opakování úkolu

def nasobeni(l1, l2):
    dot = 0
    for i, j in zip(l1, l2):        # zip prochází oba seznamy a vezme odpovídající záznamy (se stejným indexem)
        dot += i*j
    #dot2 = 0
    #for i in range(mez):
    #    dot2 += l1[i]*l2[i]
    return dot


list1 = list(range(mez))            # čísla od 0 až do mez-1
list2 = list(range(mez))

start = process_time()              # začátek měření času
for i in range(opak):
    dot = nasobeni(list1, list2)
end = process_time()                # konec měření času

print(dot)
print(type(dot))
print("Čas:", round(end - start, 10))

333328333350000
<class 'int'>
Čas: 1.375


Pomocí NumPy

In [ ]:
import numpy as np
from time import process_time
mez = 100000                        # velikost vektoru
opak = 100                          # počet opakování úkolu
arr1 = np.arange(mez, dtype=np.int64)
arr2 = np.arange(mez, dtype=np.int64)

start = process_time()              # začátek měření času
for i in range(opak):
    dot = arr1 @ arr2
    #dot = np.dot(arr1, arr2)
end = process_time()                # konec měření času

print(dot)
print(type(dot))
print("Čas:", round(end - start, 10))

333328333350000
<class 'numpy.int64'>
Čas: 0.0


#### Výpočet funkčních hodnot

Klasicky (bez NumPy)

In [ ]:
import math
mez = 1000000                       # velikost vektoru

list1 = list(range(mez))            # první seznam
list2=[0]*mez                       # vektor výsledků, zatím samé nuly
print(list1[:20])                   # prvních 20 prvků

start = process_time()
for i in range(len(list2)):
    list2[i]=math.sin(list1[i])
print(list2[:10])                   # výsledky (prvních 10)
end = process_time()
print("Čas:", round(end - start, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0.0, 0.8414709848078965, 0.9092974268256817, 0.1411200080598672, -0.7568024953079282, -0.9589242746631385, -0.27941549819892586, 0.6569865987187891, 0.9893582466233818, 0.4121184852417566]
čas: 0.328125


Pomocí NumPy

In [ ]:
arr1 = np.arange(mez, dtype=np.int64)   # první seznam
print(arr1[:20])                        # prvních 20 prvků

start = process_time()
arr2 = np.sin(arr1)                     # výpočet vektorově
print(arr2[:10])                        # výpis v kompaktnější formě (prvních 10)
print(format(arr2[1],'.16f'))           # přesnost stejná
end = process_time()
print("Čas:", round(end - start, 10))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
0.8414709848078965
čas: 0.015625


In [ ]:
import numpy as np
from time import process_time

def my_func(x):
    y = x**3 - 2*x + 5
    if y>0.5:
        return y-0.5
    else:
        return 0

r =  range(100000)              # velikost vektoru (např. 100 000)
v = np.array(r)
opak = 10
t0 = process_time()

for i in range(opak):           # bez numpy, cyklus for
    a1 = [my_func(p) for p in r]
t1 = process_time()

for i in range(opak):           # s numpy, ale nepřímé provádění
    a2 = np.vectorize(my_func)(v)
t2 = process_time()

my_func_vec = np.vectorize(my_func)
for i in range(opak):           # totéž, nepomůže
    a3 = my_func_vec(v)
t3 = process_time()

#---------------------------------------
def my_func_vectorized(x):      # funkce pracující vektorově
    y = x**3 - 2*x + 5
    y = np.maximum(y - 0.5, 0)
    return y
 
for i in range(opak):           # vektorová funkce
    a3 = my_func_vectorized(v)
t4 = process_time()

for i in range(opak):           # vektorová funkce bez numpy
    a1 = [my_func_vectorized(p) for p in r]
t5 = process_time()


print("klas. for:", t1-t0)
print("np-nepř.1:", t2-t1)
print("np-nepř.2:", t3-t2)
print("vektorově:", t4-t3)
print("v. bez np:", t5-t4)

klas. for: 0.53125
np-nepř.1: 0.59375
np-nepř.2: 0.578125
vektorově: 0.015625
v. bez np: 2.375


#### Mazání

Klasicky (bez NumPy)

In [ ]:
list1 = list(range(mez))
start = process_time()
del list1
end = process_time()
round(end - start, 10)

0.015625

Pomocí NumPy

In [ ]:
arr1 = np.arange(mez, dtype=np.int64)
start = process_time()
del arr1
end = process_time()
round(end - start, 10)

0.0

https://numpy.org/devdocs/reference/routines.linalg.html