# NumPy

Základní vědecká a analytická knihovna pro vědecké výpočty a manipulaci s daty

- n-rozměrné homogenní pole
- API pro práci s ním
- operace přímo nad poli bez nutnosti iterací
- jednoduché použití

implementace v jazyce C
- efektivnější operace
- vysoký výkon

základ pro mnoho dalších knihoven:
- Pandas: Pro analýzu dat
- SciPy: Pro pokročilé vědecké výpočty
- Matplotlib: Pro vizualizaci dat
- TensorFlow a PyTorch: Pro strojové učení

Instalace

In [7]:
!python -m pip install numpy

Defaulting to user installation because normal site-packages is not writeable


V případě potřeby aktualizace Pip Package Installer

In [8]:
!python -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable


## Jednoduché datové typy
např. int64, int16, float16, float128, complex128, ap.

In [3]:
import numpy as np
for typ in np.ScalarType: print(typ)

<class 'int'>
<class 'float'>
<class 'complex'>
<class 'bool'>
<class 'bytes'>
<class 'str'>
<class 'memoryview'>
<class 'numpy.bool'>
<class 'numpy.complex64'>
<class 'numpy.complex128'>
<class 'numpy.clongdouble'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.longdouble'>
<class 'numpy.int8'>
<class 'numpy.int16'>
<class 'numpy.intc'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.datetime64'>
<class 'numpy.timedelta64'>
<class 'numpy.object_'>
<class 'numpy.bytes_'>
<class 'numpy.str_'>
<class 'numpy.uint8'>
<class 'numpy.uint16'>
<class 'numpy.uintc'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.void'>


In [10]:
import numpy as np
import sys, math
a = math.sqrt(2)                    # klasická math
print("Math:", a, type(a), sys.getsizeof(a), "B")
print("Numpy:")
b = np.sqrt(2)                      # nebo b = np.double(np.sqrt(2))
print(b, type(b), sys.getsizeof(b), "B")

c = np.longdouble(np.sqrt(2))       # může mít vyšší přesnost (až 80 b)
print(c, type(c), sys.getsizeof(c), "B")

Math: 1.4142135623730951 <class 'float'> 24 B
Numpy:
1.4142135623730951 <class 'numpy.float64'> 32 B
1.4142135623730951 <class 'numpy.longdouble'> 32 B


## Definice polí

Numpy pole 
- pole hodnot
- všechny stejného typu (staticky typovaná, homogenní)
- indexováno n-ticí nezáporných celých čísel

Seznam 
- pythonovský ekvivalent pole
- lze měnit jeho velikost
- může obsahovat prvky různých typů

Výhody NumPy pole
- menší velikost v paměti
- vyšší výkon (optimalizace)
    - výpočty prováděny v kompilovaném jazyce (C/Fortran)
- další implementované funkce (sčítání, násobení, ...)

#### Způsoby vytvoření numpy pole
* z nějakého kontejneru (seznam, n-tice, ...)
* pomocí funkce numpy (arange, linspace, zeros, full, ...)
* načtením ze souboru

In [11]:
import numpy as np
vector = np.array([1, 2, 3, 4])                   # vektor int (ze seznamu)
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # pole 3 × 3
display(vector)
display(a1)

array([1, 2, 3, 4])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Srovnání se seznamem (list)

In [12]:
seznam = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]      # seznam (list)
seznam

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Srovnání velikostí seznamu a pole

In [13]:
import sys
a1 = np.array(seznam)                           # seznam -> pole
print(a1)
print(seznam)
# velikosti
print("Pole:  ", sys.getsizeof(a1))
print("Seznam:", sys.getsizeof(seznam))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Pole:   200
Seznam: 80


Velikost menší pro větší seznamy

In [14]:
seznam = list(range(100))
a1 = np.array(seznam)
print("Pole:  ", sys.getsizeof(a1))
print("Seznam:", sys.getsizeof(seznam))

Pole:   912
Seznam: 856


#### Vlastnosti pole
- tvar (velikost) pole - **shape** (např. matice 3×3)
- datový typ pole - **dtype** (typ prvků)

Pole celých čísel

In [15]:
a1 = np.array([             # pole intererů
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])             # pole 3 × 3
print(a1.shape)             # tvar (-> n-tice)
print(a1.size)              # počet prvků
print(sys.getsizeof(a1))    # velikost
a1.dtype                    # typ

(3, 3)
9
200


dtype('int64')

Pole čísel s pohyblivou řádovou čárkou

In [16]:
a1 = np.array([             # pole floatů
    [1, 2, 3.0],
    [4, 5, 6],
    [7, 8, 9]])             # pole 3 × 3
print(a1.shape)             # tvar (-> n-tice)
print(a1.size)              # počet prvků
print(sys.getsizeof(a1))    # velikost
a1.dtype      

(3, 3)
9
200


dtype('float64')

Datový typ můžeme specifikovat už při vytváření pole

In [17]:
matice = np.array([[1, 2], [3, 4]], dtype=complex)
display(matice.dtype)
matice

dtype('complex128')

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Pole větších řádů

In [18]:
krychle = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Shape:", krychle.shape)        # tvar
print("Size: ", krychle.size)         # počet prvků
print("ndim: ", krychle.ndim)         # dimenze
display(krychle)


Shape: (2, 2, 2)
Size:  8
ndim:  3


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## Základní operace s poli
- probíhá po všech prvcích

In [19]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])    # vytvoření pole 3 × 3
a1                                                  # výpis pole

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Přičtení skalární hodnoty

In [20]:
display(a1 - 1)             # přičtení skaláru
display(-a1)                # změna znamének

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

Násobení skalární hodnotou

In [21]:
display(a1 * 2)             # násobení skalárem
display(a1 / 2)             # dělení skalárem (float)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

Celočíselné dělení

In [22]:
display(a1 // 2)            # celočíselné
display(a1 % 2)             # zbytek

array([[0, 1, 1],
       [2, 2, 3],
       [3, 4, 4]])

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

Porovnání

In [23]:
a1 > 3                      # porovnání se skalárem

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

Logické spojení operací přes bitové operátory "&" (*a*) a "|" (*nebo*)
- neintuitivní priorita - <font color="red">nutno závorkovat!</font>
- (Python neumožňuje předefinovat chování operátorů and a or)

In [24]:
(a1 > 3) & (a1 < 7)

array([[False, False, False],
       [ True,  True,  True],
       [False, False, False]])

## Operace s více poli
opět po prvcích

definujeme druhé pole

In [25]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])    # pole 3 × 3
a2 = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]])    # pole 3 × 3
a1, a2                  # výpis obou polí

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[0, 1, 0],
        [1, 0, 1],
        [0, 1, 0]]))

Sčítání polí

In [26]:
a1 + a2                 # sčítání po prvcích

array([[1, 3, 3],
       [5, 5, 7],
       [7, 9, 9]])

Násobení (po prvcích)
- neodpovídá maticovému násobení

In [27]:
a1 * a2                 # násobení po prvcích

array([[0, 2, 0],
       [4, 0, 6],
       [0, 8, 0]])

Seznam převeden na pole automaticky

In [28]:
seznam = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]          # seznam (list)
print(seznam)
display(a1 * seznam)            # pole * seznam je pole
a1 + seznam                     # pole + seznam je pole

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

## Indexování, výběr

In [29]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])    # pole 3 × 3
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Pole se chová jako sekvence menších polí
- 1. řádek

In [30]:
a1[0]            # 1. řádek

array([1, 2, 3])

- poslední řádek

In [31]:
a1[-1]           # poslední řádek

array([7, 8, 9])

- rozsah

In [32]:
a1[:-1]          # 1. až předposlední

array([[1, 2, 3],
       [4, 5, 6]])

- prvek

In [33]:
a1[0][1]         # 1. řádek, 2. sloupec

np.int64(2)

- přístup k prvku v NumPy lze i pomocí n-tice

In [34]:
a1[0, 1]         # 1. řádek, 2. sloupec

np.int64(2)

In [35]:
a1[:-1, 1:]      # 1. až předposlední řádek, od 2. sloupce

array([[2, 3],
       [5, 6]])

Výběr řádku a sloupce
- pomocí ":"

In [36]:
display(a1[2])      # 3. řádek
a1[2, :]            # 3. řádek (totéž jako a1[2])

array([7, 8, 9])

array([7, 8, 9])

In [37]:
a1[:, 2]     # 3. sloupec

array([3, 6, 9])

Pozor na editaci!
- jedná se o stejné pole

In [38]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # pole 3 × 3
v = a1[1, :]        # 2. řádek (totéž jako a1[1])
display(v)
v[-1] = 0           # editujeme vektor
a1                  # ovlivní to matici

array([4, 5, 6])

array([[1, 2, 3],
       [4, 5, 0],
       [7, 8, 9]])

odkaz na původní objekt, ze kterého bylo pole vytvořeno

In [39]:
display(v.base)         # původní objekt
print(v.base is a1)     # True
print(a1.copy().base)   # kopie nemá žádný vztah k pův. objektu

array([[1, 2, 3],
       [4, 5, 0],
       [7, 8, 9]])

True
None


Řezy pomocí indexů

In [40]:
import numpy as np
v = np.array(range(21))         # čísla od 0 do 20
v *= 10                         # [0, 10 ... 200]
print(v)
indexy = [1,3,10]
v[indexy]                       # neboli v[[1,3,10]]

[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180 190 200]


array([ 10,  30, 100])

Výběr prvků pomocí pole logických hodnot

In [41]:
display(a1)
vetsi = a1 > 4          # vpravo matice, obsahuje True a False
display(vetsi)          # pole logických hodnot
a1[vetsi]               # pole prvků (jednorozměrné)

array([[1, 2, 3],
       [4, 5, 0],
       [7, 8, 9]])

array([[False, False, False],
       [False,  True, False],
       [ True,  True,  True]])

array([5, 7, 8, 9])

Změna pořadí řádků a sloupců, kopie řádků a sloupců

In [42]:
display(a1[1])          # 2. řádek
display(a1[[1]])        # pole obsahující 2. řádek
a1[[0, 2, 1, 1]]        # řádky 0, 2, 1 a 1 (pole obsahující tyto řádky)

array([4, 5, 0])

array([[4, 5, 0]])

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 0],
       [4, 5, 0]])

In [43]:
a1[:, [2, 2, 0, 0]]      # sloupce 2, 2, 0, 0

array([[3, 3, 1, 1],
       [0, 0, 4, 4],
       [9, 9, 7, 7]])

## Operace s různě velkými poli
- odpovídající dimenze se "rozšíří" (jako u skaláru) - broadcasting

Přičtení vektoru

In [44]:
b = np.array([1, 0, 10])        # velikost 3 (stejná jako matice a1)
display(a1)
display(b)
display(a1 + b)                 # přičtení vektoru ke všem řádkům
#display(a1 + b[:,np.newaxis])  # kdybychom chtěli přičíst ke sloupcům

c = np.array([1, 0])            # (jiné velikosti) - chyba
b + c

array([[1, 2, 3],
       [4, 5, 0],
       [7, 8, 9]])

array([ 1,  0, 10])

array([[ 2,  2, 13],
       [ 5,  5, 10],
       [ 8,  8, 19]])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
print("Původní:\n", a1)
print("Přičtení řádkového vektoru:\n", a1 + [1, 0, 10])
print("Násobení řádkovým vektorem:\n", a1 * [1, 0, 10])
print("Násobení sloupcovým vektorem:\n", a1 * [[1], [0], [10]])

Původní:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Přičtení řádkového vektoru:
 [[ 2  2 13]
 [ 5  5 16]
 [ 8  8 19]]
Násobení řádkovým vektorem:
 [[ 1  0 30]
 [ 4  0 60]
 [ 7  0 90]]
Násobení sloupcovým vektorem:
 [[ 1  2  3]
 [ 0  0  0]
 [70 80 90]]


## Editace polí

In [ ]:
a1[0, 0] = 100               # jedna z možností
a1[1][1] = 200               # jiný způsob
a1

array([[100,   2,   3],
       [  4, 200,   6],
       [  7,   8,   9]])

lze měnit jakýkoliv výběr, funguje rozšiřování (broadcasting)

In [ ]:
a1[0] = 100          # první řádek
print(a1)
a1[:, 1] = 500       # druhý sloupec
print(a1)
a1[:] = 100          # všechny prvky
a1

[[100 100 100]
 [  4 200   6]
 [  7   8   9]]
[[100 500 100]
 [  4 500   6]
 [  7 500   9]]


array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

Editace rozšířeným přiřazením

In [ ]:
a1 *= 2
a1

array([[200, 200, 200],
       [200, 200, 200],
       [200, 200, 200]])

Operace array = array * 2 dává stejný výsledek, ale vytvoří nové pole, které pak přiřadí do původní proměnné

## Tvoření matic pomocí funkcí

Naplnění matice m × n libovolným stejným číslem

In [ ]:
np.full((4, 4), 3.14)                    # tvar, hodnota

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

Naplnění matice m × n nulami (jedničkami)

In [ ]:
np.zeros((4, 4)), np.ones((4, 4))     # nuly, jedničky

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

Jednotková a diagonální matice (vždy čtvercové)

In [ ]:
display(np.eye(4))                  # dimenze
display(np.diag([1, 2, 3, 4]))      # prvky diagonály
np.diagonal(np.diag([9,8,7]))       # vrátí diagonálu jako vektor

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

array([9, 8, 7])

Vždy lze specifikovat datový typ

In [ ]:
int_zeros = np.zeros((4, 4), dtype='int8')
print(int_zeros.dtype)
int_zeros

int8


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

### Generování jednorozměrného pole

arange(start, stop, step)
- začátek, konec, přírůstek
- pod. jako range()

In [ ]:
print(np.arange(20))             # 0 až 19
print(np.arange(4, 20, 2))       # od, do, přírůstek

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 4  6  8 10 12 14 16 18]


Jdou i reálná čísla, ale pozor na chyby

In [ ]:
pole = np.arange(0.0, 20.0, 0.3)
print(pole)
print(pole.size, pole.size*0.3, pole[-1])

[ 0.   0.3  0.6  0.9  1.2  1.5  1.8  2.1  2.4  2.7  3.   3.3  3.6  3.9
  4.2  4.5  4.8  5.1  5.4  5.7  6.   6.3  6.6  6.9  7.2  7.5  7.8  8.1
  8.4  8.7  9.   9.3  9.6  9.9 10.2 10.5 10.8 11.1 11.4 11.7 12.  12.3
 12.6 12.9 13.2 13.5 13.8 14.1 14.4 14.7 15.  15.3 15.6 15.9 16.2 16.5
 16.8 17.1 17.4 17.7 18.  18.3 18.6 18.9 19.2 19.5 19.8]
67 20.099999999999998 19.8


linspace
- pro reálná čísla vhodnější - rovnoměrné dělení
- začátek a konec intervalu plus počet prvků

In [ ]:
np.linspace(0, 20, num=30)

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

logspace
- logaritmická stupnice

In [ ]:
np.logspace(0, 10, 11, base=10)

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07,
       1.e+08, 1.e+09, 1.e+10])

Pole s náhodnými hodnotami

In [ ]:
# několik náhodných čísel z <0, 1) s rovnoměrným rozdělením
display(np.random.random_sample(4))
# matice s náhodnými čísly s normálním rozdělením N(0,1)
np.random.standard_normal((4, 4))

array([0.09454424, 0.28429209, 0.99011091, 0.38305256])

array([[ 0.95823235, -0.81872668,  1.12751329,  0.60382383],
       [ 0.01791726,  0.69301244, -1.94585043,  0.14965595],
       [-3.01436584, -0.50804579, -0.00866734,  1.76990919],
       [ 0.45848994,  0.71082575, -1.02927885,  1.03992213]])

## Změna tvaru pole

In [ ]:
a1 = np.arange(12)            # výchozí pole
display(a1)
display(a1.shape)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

(12,)

reshape
- musí odpovídat velikost

In [ ]:
a2 = a1.reshape((3, 4))         # řádky, sloupce
a3 = a1.reshape((4, 3))
a2, a3

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

- nahradíme-li jedno z čísel -1, dopočítá se 

In [ ]:
a2 = a1.reshape((-1, 4))         # řádky, sloupce
a3 = a1.reshape((4, 3))
a3 = a1.reshape((-1, 3))
a2, a3

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [ ]:
C = np.arange(2).reshape(-1,1)   # sloupec 0,1
R = np.arange(2).reshape(1,-1)   # řádek 0,1
print(C.shape, R.shape)
display(C)
display(R)
C + R                               # broadcasting

(2, 1) (1, 2)


array([[0],
       [1]])

array([[0, 1]])

array([[0, 1],
       [1, 2]])

Pozor na editaci!
- jedná se o stejné pole

In [ ]:
a2[2,2] = 100               # 3. řádek, 3. sloupec (pův. 10)
a2, a1, a3               # editovalo se jen a2

(array([[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9, 100,  11]]),
 array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100,  11]),
 array([[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9, 100,  11]]))

Pro kopii dat copy

In [ ]:
a2 = a1.reshape((3, 4)).copy()
a2[2, 2] = 10
a2, a3

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9, 100,  11]]))

Transpozice

In [ ]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
v = np.array([1,3,7])
display(v)
display(v.T)        # transpozice vektoru je v numpy stejný vektor
v == v.T

array([1, 3, 7])

array([1, 3, 7])

array([ True,  True,  True])

Přidání další osy pomocí newaxis
- rozšíření rozměrů pole o jednu novou osu (nová osa obvykle přidána na začátek pole)

In [ ]:
import numpy as np
arr = np.array([1, 2, 3])           # Původní pole (1D)
arr_2d = arr[:, np.newaxis]         # Přidání nové osy, čímž vytvoříme 2D pole
arr_2d

array([[1],
       [2],
       [3]])

In [ ]:
arr_2d = np.array([[1, 2, 3],       # Původní 2D pole (3x3)
                   [4, 5, 6],
                   [7, 8, 9]])
arr_3d = arr_2d[:, :, np.newaxis]   # Přidání nové osy do druhé dimenze, čímž vytvoříme 3D pole
print(arr_3d.shape)                 # Výstup: (3, 3, 1)
arr_3d

(3, 3, 1)


array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

Skládání polí - stacking (concatenate)

In [ ]:
arr1 = np.arange(1,10).reshape(3,3)     # příprava matic
arr2 = 2*arr1
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
arr3=np.hstack((arr1, arr2))        # horizontální skládání
#arr3=np.concatenate((arr1, arr2), axis=1)
arr3

array([ 4,  5,  6,  8, 10, 12])

In [ ]:
arr3=np.vstack((arr1, arr2))        # vertikální skládání
#arr3=np.concatenate((arr1, arr2), axis=0)
arr3

[[ 4  8]
 [ 5 10]
 [ 6 12]]


array([[ 4,  5,  6],
       [ 8, 10, 12]])

In [ ]:
print(arr1)
print(arr2)

arr3=np.dstack((arr1, arr2))    # složení přes osu z (depth)
display(arr3)                   # dimenze 3, vnitřní vektor 1. složka arr1, 2. složka arr2

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])

Pro 1D pole můžeme použít funkce column_stack a row_stack

In [ ]:
arr1 = np.arange(4,7) 
arr2 = 2 * arr1
print(arr1)
print(arr2)
print()

# column stack
arr_col_stack = np.column_stack((arr1,arr2))
print(arr_col_stack)
print(np.hstack((arr1.T,arr2.T)))    # transpozice nemá vliv na 1D pole

# row stack
arr_row_stack = np.row_stack((arr1,arr2)) 
print(arr_row_stack)
print(np.vstack((arr1,arr2)))


[4 5 6]
[ 8 10 12]

[[ 4  5  6]
 [ 8 10 12]]
[[ 4  8]
 [ 5 10]
 [ 6 12]]
[ 4  5  6  8 10 12]
[[ 4  5  6]
 [ 8 10 12]]
[[ 4  5  6]
 [ 8 10 12]]


Dělení matice (opačný proces): split 
- hsplit - pole sloupců
- vsplit - pole řádků

In [ ]:
arr=np.arange(1,10).reshape(3,3)
print(arr)

# vodorovné dělení (na sloupce)
np.hsplit(arr, 3)    # nebo np.split(arr,3,axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [ ]:
# svislé dělení (na řádky)
np.vsplit(arr, 3)    # nebo np.split(arr,3,axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

## Datové typy polí

In [ ]:
print(np.zeros(4, dtype=int))        # pro matici (4,4)
print(np.zeros(4, dtype=float))
print(np.zeros(4, dtype=bool))

[0 0 0 0]
[0. 0. 0. 0.]
[False False False False]


Změna datového typu

In [ ]:
arr=np.arange(1,10).reshape(3,3)
print(arr)

arr=arr.astype(float)
print(arr)
print("Změněný typ:", arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Změněný typ: float64


Pokud uložíme různé datové typy, výsledkem je defaultně string 

(zde little-endian 32 character string)

In [ ]:
np.array([0, 3.14, "ahoj"])

array(['0', '3.14', 'ahoj'], dtype='<U32')

Nejobecnější typ je object

In [ ]:
np.array([0, 3.14, "ahoj"], dtype=object)

array([0, 3.14, 'ahoj'], dtype=object)

Další možnosti: Klasické řetězcové specifikace, bytestring (ukončeny \0), složené datové typy (records)

## Maticové násobení
- původně funkce dot, od Pythonu 3.5 operátor @ (mATrix multiplication),

Násobení matice vektorem

In [ ]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([1, 0, 0])
array1 @ vector, np.dot(array1, vector), array1.dot(vector)

(array([1, 4, 7]), array([1, 4, 7]), array([1, 4, 7]))

Násobení dvou matic

In [ ]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]])
array1 @ array2, np.dot(array1, array2), array1.dot(array2)

(array([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]]),
 array([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]]),
 array([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]]))

Neodpovídající rozměry

In [ ]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([1, 0, 0])
vector @ array1                         # automatická transpozice

array([1, 2, 3])

In [ ]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([1, 0])            # pouze 2 hodnoty - chyba
vector @ array1

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

## Booleovské hodnoty polí

In [ ]:
E = np.eye(3)
if E.any():                         # obsahuje cokoliv nenulového
    print('Alespoň jeden prvek je nenulový')
if E.all():                         # všechny prvky nenulové
    print('Všechny prvky jsou nenulové')
print(E.size)
if E.size:                          # počet prvků
    print('Pole obsahuje nějaké prvky')

Alespoň jeden prvek je nenulový
9
Pole obsahuje nějaké prvky


## Iterace

In [2]:
import numpy as np
v = np.array([1, 2, 3, 4])

for element in v:
    print(element)

1
2
3
4


Iteruje se přes první index (po řádcích)

In [30]:
M = np.array([[1, 2], [3, 4]])

for row in M:
    print(f"row: {row}")

row: [1 2]
row: [3 4]


Přístup k indexům přes enumerate

In [33]:
v = np.array([1, 2, 3, 4])
for i, p in enumerate(v):
    print(f"prvek č. {i}: {p}")

prvek č. 0: 1
prvek č. 1: 2
prvek č. 2: 3
prvek č. 3: 4


In [35]:
M = np.array([[1, 2], [3, 4]])

for row_idx, row in enumerate(M):
    print(f"řádek č. {row_idx}: {row}")
    
    for col_idx, element in enumerate(row):
        print(f"  prvek {element} ve sloupci {col_idx}")
       
        # update the matrix M: square each element
        M[row_idx, col_idx] = element ** 2
M

řádek č. 0: [1 2]
  prvek 1 ve sloupci 0
  prvek 2 ve sloupci 1
řádek č. 1: [3 4]
  prvek 3 ve sloupci 0
  prvek 4 ve sloupci 1


array([[ 1,  4],
       [ 9, 16]])

## Vektorové funkce
např. vytvoříme hodnoty z intervalu 0 až $\pi$ s dělením na 1000 dílků a spočítáme sinus 

In [ ]:
#                     od,       do,   dělení   
a1 = np.linspace(0, np.pi, num=1000)   # vytvoření pole
a1[:10]                                      # výpis prvních 10 prvků

array([0.        , 0.00314474, 0.00628947, 0.00943421, 0.01257895,
       0.01572369, 0.01886842, 0.02201316, 0.0251579 , 0.02830264])

In [ ]:
sinus = np.sin(a1)                        # použití funkce sin
sinus[:10]                                      # výpis prvních 10 prvků

array([0.        , 0.00314473, 0.00628943, 0.00943407, 0.01257862,
       0.01572304, 0.0188673 , 0.02201138, 0.02515525, 0.02829886])

### Vektorizace funkcí
požadujeme, aby argumentem i výsledkem funkce byl vektor

In [2]:
def Theta(x):
    """
    Scalar implemenation of the Heaviside step function.
    """
    if x >= 0:
        return 1
    else:
        return 0

In [ ]:
# toto bychom chtěli, ale nebude fungovat
Theta(np.array([-3, -2, -1, 0, 1, 2, 3]))

In [4]:
import numpy as np
Theta_vec = np.vectorize(Theta)
Theta_vec(np.array([-3, -2, -1, 0, 1, 2, 3]))

array([0, 0, 0, 1, 1, 1, 1])

Vhodnější vektorová funkce

In [5]:
def Theta_numpy(x):
    """
    Vector-aware implemenation of the Heaviside step function.
    """
    return 1 * (x >= 0)

In [6]:
Theta_numpy(np.array([-3, -2, -1, 0, 1, 2, 3]))

array([0, 0, 0, 1, 1, 1, 1])

Porovnání rychlosti pomocí magického příkazu %timeit

In [7]:
randvec = np.random.random_sample((10000)) * 2000 - 1000
%timeit Theta_vec(randvec)
%timeit Theta_numpy(randvec)

1.89 ms ± 171 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
21.4 µs ± 378 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## Práce se soubory
Nejdříve vytvoříme textový soubor s daty
- writefile (file) - magický příkaz, vytvoří soubor a zapíše do něj to, co následuje

In [1]:
%%writefile tmp/ascii_data_1.txt         
 1    -6.1    -6.1    -6.1 1
 2   -15.4   -15.4   -15.4 1
 3   -15.0   -15.0   -15.0 1
 4   -19.3   -19.3   -19.3 1
 5   -16.8   -16.8   -16.8 1
 6   -11.4   -11.4   -11.4 1
 7    -7.6    -7.6    -7.6 1
 8    -7.1    -7.1    -7.1 1
 9   -10.1   -10.1   -10.1 1
10    -9.5    -9.5    -9.5 1

Writing tmp/ascii_data_1.txt


Pokusíme se načíst data ze souboru

In [4]:
data1 = np.genfromtxt('tmp/ascii_data_1.txt')
data2 = np.loadtxt('tmp/ascii_data_1.txt')
#print(data1 == data2)
data1, data2

(array([[  1. ,  -6.1,  -6.1,  -6.1,   1. ],
        [  2. , -15.4, -15.4, -15.4,   1. ],
        [  3. , -15. , -15. , -15. ,   1. ],
        [  4. , -19.3, -19.3, -19.3,   1. ],
        [  5. , -16.8, -16.8, -16.8,   1. ],
        [  6. , -11.4, -11.4, -11.4,   1. ],
        [  7. ,  -7.6,  -7.6,  -7.6,   1. ],
        [  8. ,  -7.1,  -7.1,  -7.1,   1. ],
        [  9. , -10.1, -10.1, -10.1,   1. ],
        [ 10. ,  -9.5,  -9.5,  -9.5,   1. ]]),
 array([[  1. ,  -6.1,  -6.1,  -6.1,   1. ],
        [  2. , -15.4, -15.4, -15.4,   1. ],
        [  3. , -15. , -15. , -15. ,   1. ],
        [  4. , -19.3, -19.3, -19.3,   1. ],
        [  5. , -16.8, -16.8, -16.8,   1. ],
        [  6. , -11.4, -11.4, -11.4,   1. ],
        [  7. ,  -7.6,  -7.6,  -7.6,   1. ],
        [  8. ,  -7.1,  -7.1,  -7.1,   1. ],
        [  9. , -10.1, -10.1, -10.1,   1. ],
        [ 10. ,  -9.5,  -9.5,  -9.5,   1. ]]))

Opětovné uložení

In [5]:
np.savetxt("tmp/ascii_data_1_new.txt", data1, fmt="%6g")     # uložíme pod jiným jménem
print(open("tmp/ascii_data_1_new.txt", "r").read())             # přesvědčíme se

     1   -6.1   -6.1   -6.1      1
     2  -15.4  -15.4  -15.4      1
     3    -15    -15    -15      1
     4  -19.3  -19.3  -19.3      1
     5  -16.8  -16.8  -16.8      1
     6  -11.4  -11.4  -11.4      1
     7   -7.6   -7.6   -7.6      1
     8   -7.1   -7.1   -7.1      1
     9  -10.1  -10.1  -10.1      1
    10   -9.5   -9.5   -9.5      1



Je možné používat i vlastní NumPy formát, příkazy jsou stejné bez txt (save, load)

## Cvičení: Srovnání rychlosti

#### Součet vektorů

In [ ]:
import time
import numpy as np

velikostVektoru = 1000000

def SoucetSeznamy1():                   # klasické for
    t1 = time.time()
    X = range(velikostVektoru)
    Y = range(velikostVektoru)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1

def SoucetSeznamy():
    t1 = time.time()
    X = range(velikostVektoru)
    Y = range(velikostVektoru)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - t1

def SoucetNumPy():                      # numpy
    t1 = time.time()
    X = np.arange(velikostVektoru)
    Y = np.arange(velikostVektoru)
    Z = X + Y
    return time.time() - t1

print(SoucetSeznamy1())
t1 = SoucetSeznamy()
t2 = SoucetNumPy()
print(t1)
print(t2)
if t2 != 0:
    print("Numpy je rychlejší {:.2f}×".format(t1/t2))
else:
    print("Podíl nelze stanovit")

0.3661055564880371
0.28478312492370605
0.004105329513549805
Numpy je rychlejší 69.37×


#### Násobení vektorů

Klasicky (bez NumPy)

In [7]:
from time import process_time
mez = 100000                        # velikost vektoru
opak = 100                          # počet opakování úkolu

def nasobeni(l1, l2):
    dot = 0
    for i, j in zip(l1, l2):        # zip prochází oba seznamy a vezme odpovídající záznamy (se stejným indexem)
        dot += i*j
    #dot2 = 0
    #for i in range(mez):
    #    dot2 += l1[i]*l2[i]
    return dot


list1 = list(range(mez))            # čísla od 0 až do mez-1
list2 = list(range(mez))

start = process_time()              # začátek měření času
for i in range(opak):
    dot = nasobeni(list1, list2)
end = process_time()                # konec měření času

print(dot)
print(type(dot))
print("Čas:", round(end - start, 10))

333328333350000
<class 'int'>
Čas: 1.375


Pomocí NumPy

In [32]:
import numpy as np
from time import process_time
mez = 100000                        # velikost vektoru
opak = 100                          # počet opakování úkolu
arr1 = np.arange(mez, dtype=np.int64)
arr2 = np.arange(mez, dtype=np.int64)

start = process_time()              # začátek měření času
for i in range(opak):
    dot = arr1 @ arr2
    #dot = np.dot(arr1, arr2)
end = process_time()                # konec měření času

print(dot)
print(type(dot))
print("Čas:", round(end - start, 10))

333328333350000
<class 'numpy.int64'>
Čas: 0.0


#### Výpočet funkčních hodnot

Klasicky (bez NumPy)

In [3]:
import math
mez = 1000000                       # velikost vektoru

list1 = list(range(mez))            # první seznam
list2=[0]*mez                       # vektor výsledků, zatím samé nuly
print(list1[:20])                   # prvních 20 prvků

start = process_time()
for i in range(len(list2)):
    list2[i]=math.sin(list1[i])
print(list2[:10])                   # výsledky (prvních 10)
end = process_time()
print("Čas:", round(end - start, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0.0, 0.8414709848078965, 0.9092974268256817, 0.1411200080598672, -0.7568024953079282, -0.9589242746631385, -0.27941549819892586, 0.6569865987187891, 0.9893582466233818, 0.4121184852417566]
čas: 0.328125


Pomocí NumPy

In [ ]:
arr1 = np.arange(mez, dtype=np.int64)   # první seznam
print(arr1[:20])                        # prvních 20 prvků

start = process_time()
arr2 = np.sin(arr1)                     # výpočet vektorově
print(arr2[:10])                        # výpis v kompaktnější formě (prvních 10)
print(format(arr2[1],'.16f'))           # přesnost stejná
end = process_time()
print("Čas:", round(end - start, 10))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
0.8414709848078965
čas: 0.015625


In [21]:
import numpy as np
from time import process_time

def my_func(x):
    y = x**3 - 2*x + 5
    if y>0.5:
        return y-0.5
    else:
        return 0

r =  range(100000)              # velikost vektoru (např. 100 000)
v = np.array(r)
opak = 10
t0 = process_time()

for i in range(opak):           # bez numpy, cyklus for
    a1 = [my_func(p) for p in r]
t1 = process_time()

for i in range(opak):           # s numpy, ale nepřímé provádění
    a2 = np.vectorize(my_func)(v)
t2 = process_time()

my_func_vec = np.vectorize(my_func)
for i in range(opak):           # totéž, nepomůže
    a3 = my_func_vec(v)
t3 = process_time()

#---------------------------------------
def my_func_vectorized(x):      # funkce pracující vektorově
    y = x**3 - 2*x + 5
    y = np.maximum(y - 0.5, 0)
    return y
 
for i in range(opak):           # vektorová funkce
    a3 = my_func_vectorized(v)
t4 = process_time()

for i in range(opak):           # vektorová funkce bez numpy
    a1 = [my_func_vectorized(p) for p in r]
t5 = process_time()


print("klas. for:", t1-t0)
print("np-nepř.1:", t2-t1)
print("np-nepř.2:", t3-t2)
print("vektorově:", t4-t3)
print("v. bez np:", t5-t4)

klas. for: 0.53125
np-nepř.1: 0.59375
np-nepř.2: 0.578125
vektorově: 0.015625
v. bez np: 2.375


#### Mazání

Klasicky (bez NumPy)

In [ ]:
list1 = list(range(mez))
start = process_time()
del list1
end = process_time()
round(end - start, 10)

0.015625

Pomocí NumPy

In [ ]:
arr1 = np.arange(mez, dtype=np.int64)
start = process_time()
del arr1
end = process_time()
round(end - start, 10)

0.0

## Lineární algebra s np.linalg
Základní operace, doplněno v SciPy

Několik příkladů:

In [47]:
import numpy as np
a = np.array([[1, 2], [3, 4]])           # a1
print(a)
print(type(a))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


Výpočet determinantu

In [48]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

np.float64(-2.0000000000000004)

Výpočet hodnosti matice

In [49]:
from numpy.linalg import matrix_rank
print(a)
print("Hodnost a:", matrix_rank(a))
print("Hodnost jednotkové 4x4:", matrix_rank(np.eye(4)))

[[1 2]
 [3 4]]
Hodnost a: 2
Hodnost jednotkové 4x4: 4


In [50]:
I=np.eye(4)
I[-1,-1] = 0                # odstraníme poslední diag. hodnotu
matrix_rank(I)              # hodnost je menší

np.int64(3)

Stopa matice

In [51]:
np.trace(np.eye(3))   # součet prvků na diagonále

np.float64(3.0)

In [52]:
a = np.arange(8).reshape((2,2,2))        # 2×2×2
print(a)
np.trace(a)                              # 2 diagonály: 0+6, 1+7

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([6, 8])

Inverze matice

In [53]:
from numpy.linalg import inv
a = np.array([[1., 2.], [3., 4.]])
ainv = inv(a)           # inverzní
print(a)
print(ainv)
print(a @ ainv)         # kontrola
np.allclose(a @ ainv, np.eye(2))

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


True

## Třída Matice
pohodlné, ale nepřináší nic nového

In [55]:
A1 = np.array([1, 2, 3, 4]).reshape(2, 2)   # array
display(A1)

A = np.asmatrix('[1 2;3 4]')                # matrix (pův. np.mat)
A

array([[1, 2],
       [3, 4]])

matrix([[1, 2],
        [3, 4]])

Transpozice, inverze

In [56]:
display(A1.T, np.linalg.inv(A1))            # array
display(A.T, A.I)                           # matrix

array([[1, 3],
       [2, 4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

matrix([[1, 3],
        [2, 4]])

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

Násobení matic a vektorů

In [58]:
b = np.asmatrix('[5 6]')                     # vektor jako matice
display(b*A)
display(A*b.T)
display(b@A)
A@b.T

matrix([[23, 34]])

matrix([[17],
        [39]])

matrix([[23, 34]])

matrix([[17],
        [39]])

In [59]:
b1 = np.array([5, 6])                   # vektor jako pole
display(b1@A1)
display(A1@b1.T)
b1*A1                                   # násobení po prvcích (+ broadcasting)

array([23, 34])

array([17, 39])

array([[ 5, 12],
       [15, 24]])

https://numpy.org/devdocs/reference/routines.linalg.html