## NumPy

základní vědecká a analytická knihovna

- n-rozměrné homogenní pole
- API pro práci s ním

Instalace

In [4]:
!python -m pip install numpy

V případě potřeby aktualizace Pip Package Installer

In [3]:
!python -m pip install --upgrade pip

## Datové typy

In [3]:
import sys, numpy, math
a = math.sqrt(2)
print(a, type(a), sys.getsizeof(a))

b = numpy.sqrt(2)                       # nebo b = numpy.double(numpy.sqrt(2))
print(b, type(b), sys.getsizeof(b))

c = numpy.longdouble(numpy.sqrt(2))
print(c, type(c), sys.getsizeof(c))

1.4142135623730951 <class 'float'> 24
1.4142135623730951 <class 'numpy.float64'> 32
1.4142135623730951 <class 'numpy.longdouble'> 32


## Definice polí

Numpy pole 
- pole hodnot
- všechny stejného typu
- indexováno n-ticí nezáporných celých čísel

Seznam 
- pythonovský ekvivalent pole
- lze měnit jeho velikost
- může obsahovat prvky různých typů

Výhody NumPy pole
- menší velikost v paměti
- vyšší výkon
- optimalizované funkce (lineární algebra)

In [5]:
import numpy
vector = numpy.array([1, 2, 3, 4])                      # vektor
array = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # pole 3 × 3
vector, array

(array([1, 2, 3, 4]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

Srovnání se seznamem (list)

In [7]:
seznam = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]          # seznam (list)
seznam

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Možnost převést seznam na pole

In [8]:
a1 = numpy.array(seznam)
print(a1)
print(seznam)
# velikosti
print("Pole:", sys.getsizeof(a1))
print("Seznam:", sys.getsizeof(seznam))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Pole: 164
Seznam: 80


Velikost menší pro větší seznamy

In [26]:
seznam = list(range(100))
a1 = numpy.array(seznam)
print("Pole:", sys.getsizeof(a1))
print("Seznam:", sys.getsizeof(seznam))

Pole: 512
Seznam: 856


#### Vlastnosti pole
- tvar (velikost) pole - shape (např. matice 3×3)
- datový typ pole - shape (typ prvků)

In [14]:
array = numpy.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])             # pole 3 × 3
print(array.shape)          # tvar (-> n-tice)
print(sys.getsizeof(array)) # velikost
array.dtype                 # typ

(3, 3)
164


dtype('int32')

In [15]:
array = numpy.array([
    [1, 2, 3.0],
    [4, 5, 6],
    [7, 8, 9]])             # pole 3 × 3
print(array.shape)          # tvar (-> n-tice)
print(sys.getsizeof(array)) # velikost
array.dtype      

(3, 3)
200


dtype('float64')

Pole větších řádů

In [18]:
krychle = numpy.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(krychle.shape)
krychle

(2, 2, 2)


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## Základní operace
- probíhá po všech prvcích

In [17]:
array = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # pole 3 × 3
array                                                   # výpis pole

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Přičtení skalární hodnoty

In [20]:
array - 1, - array

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[-1, -2, -3],
        [-4, -5, -6],
        [-7, -8, -9]]))

Násobení skalární hodnotou

In [64]:
array * 2, array / 2

(array([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]),
 array([[0.5, 1. , 1.5],
        [2. , 2.5, 3. ],
        [3.5, 4. , 4.5]]))

Celočíselné dělení

In [65]:
array // 2, array % 2

(array([[0, 1, 1],
        [2, 2, 3],
        [3, 4, 4]], dtype=int32),
 array([[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]], dtype=int32))

Porovnání

In [21]:
array > 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

Logické spojení operací přes bitové operátory & (a) a | (nebo)
- neintuitivní priorita (nutno závorkovat)
- (Python neumožňuje předefinovat chování operátorů and a or)

In [67]:
(array > 3) & (array < 7)

array([[False, False, False],
       [ True,  True,  True],
       [False, False, False]])

## Operace s dalšími poli
opět po prvcích

definujeme druhé pole

In [68]:
a2 = numpy.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]])
a1, a2              # výpis obou polí

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[0, 1, 0],
        [1, 0, 1],
        [0, 1, 0]]))

Sčítání polí

In [69]:
a1 + a2

array([[1, 3, 3],
       [5, 5, 7],
       [7, 9, 9]])

Násobení (po prvcích)
- neodpovídá maticovému násobení

In [70]:
a1 * a2

array([[0, 2, 0],
       [4, 0, 6],
       [0, 8, 0]])

Seznam převeden na pole automaticky

In [71]:
print(seznam)
a1 * seznam

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

## Indexování, výběr

In [22]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Pole se chová jako sekvence menších polí
- 1. řádek

In [23]:
array[0]            # 1. řádek

array([1, 2, 3])

- poslední řádek

In [74]:
array[-1]           # poslední řádek

array([7, 8, 9])

- rozsah

In [75]:
array[:-1]          # 1. až předposlední

array([[1, 2, 3],
       [4, 5, 6]])

- prvek

In [25]:
array[0][1]         # 1. řádek, 2. sloupec

2

- přístup k prvku v NumPy lze i pomocí n-tice

In [24]:
array[0, 1]         # 1. řádek, 2. sloupec

2

In [78]:
array[:-1, 1:]      # 1. až předposlední řádek, od 2. sloupce

array([[2, 3],
       [5, 6]])

Výběr řádku a sloupce
- pomocí ":"

In [26]:
print(array[2])
array[2, :]     # 3. řádek (totéž jako array[2])

[7 8 9]


array([7, 8, 9])

In [80]:
array[:, 2]     # 3. sloupec

array([3, 6, 9])

Výběr prvků pomocí pole logických hodnot

In [28]:
print(array)
vetsi = array > 4       # vpravo matice, obsahuje True a False
print(vetsi)            # pole logických hodnot
array[vetsi]            # pole prvků

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False  True  True]
 [ True  True  True]]


array([5, 6, 7, 8, 9])

Změna pořadí řádků a sloupců, kopie řádků a sloupců

In [29]:
print(array[1])         # 2. řádek
print(array[[1]])       # pole obsahující 2. řádek
array[[0, 2, 1, 1]]     # řádky 0, 2, 1 a 1 (pole obsahující tyto řádky)

[4 5 6]
[[4 5 6]]


array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6],
       [4, 5, 6]])

In [83]:
array[:, [2, 2, 0, 0]]      # sloupce 2, 2, 0, 0

array([[3, 3, 1, 1],
       [6, 6, 4, 4],
       [9, 9, 7, 7]])

## Operace s různě velkými poli
- odpovídající dimenze se "rozšíří" (jako u skaláru) - broadcasting

Přičtení vektoru

In [51]:
b = numpy.array([1, 0, 10])       # (stejné velikosti)
print("array:\n", array)
print("b:\n", b)
print("součet:\n", array + b)

c = numpy.array([1, 0])           # (jiné velikosti) - chyba
b + c

array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b:
 [ 1  0 10]
součet:
 [[ 2  2 13]
 [ 5  5 16]
 [ 8  8 19]]


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [52]:
print("Původní:\n", array)
print("Přičtení řádkového vektoru:\n", array + [1, 0, 10])
print("Násobení řádkovým vektorem:\n", array * [1, 0, 10])
print("Násobení sloupcovým vektorem:\n", array * [[1], [0], [10]])

Původní:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Přičtení řádkového vektoru:
 [[ 2  2 13]
 [ 5  5 16]
 [ 8  8 19]]
Násobení řádkovým vektorem:
 [[ 1  0 30]
 [ 4  0 60]
 [ 7  0 90]]
Násobení sloupcovým vektorem:
 [[ 1  2  3]
 [ 0  0  0]
 [70 80 90]]


## Editace polí

In [86]:
array[0, 0] = 100               # jedna z možností
array[1][1] = 200               # jiný způsob
array

array([[100,   2,   3],
       [  4, 200,   6],
       [  7,   8,   9]])

lze měnit jakýkoliv výběr, funguje rozšiřování (broadcasting)

In [87]:
array[0] = 100          # první řádek
print(array)
array[:, 1] = 500       # druhý sloupec
print(array)
array[:] = 100          # všechny prvky
array

[[100 100 100]
 [  4 200   6]
 [  7   8   9]]
[[100 500 100]
 [  4 500   6]
 [  7 500   9]]


array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

Editace rozšířeným přiřazením

In [88]:
array *= 2
array

array([[200, 200, 200],
       [200, 200, 200],
       [200, 200, 200]])

Operace array = array * 2 dává stejný výsledek, ale vytvoří nové pole, které pak přiřadí do původní proměnné

## Tvoření matic pomocí funkcí

Naplnění matice m × n libovolným stejným číslem

In [89]:
numpy.full((4, 4), 3.14)                    # tvar, hodnota

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

Naplnění matice m × n nulami (jedničkami)

In [90]:
numpy.zeros((4, 4)), numpy.ones((4, 4))     # nuly, jedničky

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

Jednotková a diagonální matice (vždy čtvercové)

In [56]:
numpy.eye(4), numpy.diag([1, 2, 3, 4])     # dimenze, prvky diagonály

(array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 array([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]]))

Vždy lze specifikovat datový typ

In [57]:
int_zeros = numpy.zeros((4, 4), dtype='int8')
print(int_zeros.dtype)
int_zeros

int8


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

### Jednorozměrná pole

arange
- začátek, konec, přírůstek
- pod. jako range()

In [93]:
print(numpy.arange(20))             # 0 až 19
print(numpy.arange(4, 20, 2))       # od, do, přírůstek

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 4  6  8 10 12 14 16 18]


Jdou i reálná čísla, ale pozor na chyby

In [94]:
numpy.arange(0.0, 20.0, 0.3)[-1]

19.8

linspace
- pro reálná čísla vhodnější - rovnoměrné dělení
- začátek a konec intervalu plus počet prvků

In [95]:
numpy.linspace(0, 20, num=30)

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

## Změna tvaru pole

In [59]:
array = numpy.arange(12)            # výchozí pole
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

reshape
- musí odpovídat velikost

In [60]:
a2 = array.reshape((3, 4))
a3 = array.reshape((4, 3))
a2, a3

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

Pozor na editaci!
- jedná se o stejné pole

In [61]:
a2[2,2] = 100               # 3. řádek, 3. sloupec (pův. 10)
a2, array, a3               # editovalo se jen a2

(array([[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9, 100,  11]]),
 array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100,  11]),
 array([[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9, 100,  11]]))

Pro kopii dat copy

In [99]:
a2 = array.reshape((3, 4)).copy()
a2[2, 2] = 10
a2, a3

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9, 100,  11]]))

Transpozice

In [100]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## Datové typy

In [63]:
print(numpy.zeros(4, dtype=int))        # pro matici (4,4)
print(numpy.zeros(4, dtype=float))
print(numpy.zeros(4, dtype=bool))

[0 0 0 0]
[0. 0. 0. 0.]
[False False False False]


Pokud uložíme různé datové typy, výsledkem je defaultně string 

(zde little-endian 32 character string)

In [102]:
numpy.array([0, 3.14, "ahoj"])

array(['0', '3.14', 'ahoj'], dtype='<U32')

Nejobecnější typ je object

In [103]:
numpy.array([0, 3.14, "ahoj"], dtype=object)

array([0, 3.14, 'ahoj'], dtype=object)

Další možnosti: Klasické řetězcové specifikace, bytestring (ukončeny \0), složené datové typy (records)

## Maticové násobení
původně funkce dot, od Pythonu 3.5 operátor @ (mATrix multiplication),

In [104]:
array1 = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = numpy.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]])
array1 @ array2

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

## Booleovské hodnoty polí

In [71]:
E = numpy.eye(3)
if E.any():                         # obsahuje cokoliv nenulového
    print('Alespoň jeden prvek je nenulový')
if E.all():                         # všechny prvky nenulové
    print('Všechny prvky jsou nenulové')
print(E.size)
if E.size:                          # počet prvků
    print('Pole obsahuje nějaké prvky')

Alespoň jeden prvek je nenulový
9
Pole obsahuje nějaké prvky


## Aplikace funkcí
např. vytvoříme hodnoty z intervalu 0 až $\pi$ s dělením na 1000 dílků a spočítáme sinus 

In [106]:
#                     od,       do,   dělení   
array = numpy.linspace(0, numpy.pi, num=1000)   # vytvoření pole
array[:10]                                      # výpis prvních 10 prvků

array([0.        , 0.00314474, 0.00628947, 0.00943421, 0.01257895,
       0.01572369, 0.01886842, 0.02201316, 0.0251579 , 0.02830264])

In [107]:
sinus = numpy.sin(array)                        # použití funkce sin
sinus[:10]                                      # výpis prvních 10 prvků

array([0.        , 0.00314473, 0.00628943, 0.00943407, 0.01257862,
       0.01572304, 0.0188673 , 0.02201138, 0.02515525, 0.02829886])

## Práce se soubory
Nejdříve vytvoříme textový soubor s daty
- writefile (file) - magický příkaz, vytvoří soubor a zapíše do něj to, co následuje

In [112]:
%%writefile ascii_data_1.txt         
 1    -6.1    -6.1    -6.1 1
 2   -15.4   -15.4   -15.4 1
 3   -15.0   -15.0   -15.0 1
 4   -19.3   -19.3   -19.3 1
 5   -16.8   -16.8   -16.8 1
 6   -11.4   -11.4   -11.4 1
 7    -7.6    -7.6    -7.6 1
 8    -7.1    -7.1    -7.1 1
 9   -10.1   -10.1   -10.1 1
10    -9.5    -9.5    -9.5 1

Overwriting ascii_data_1.txt


Pokusíme se načíst data ze souboru

In [5]:
data1 = numpy.genfromtxt('ascii_data_1.txt')
data2 = numpy.loadtxt('ascii_data_1.txt')
#print(data1 == data2)
data1, data2

(array([[  1. ,  -6.1,  -6.1,  -6.1,   1. ],
        [  2. , -15.4, -15.4, -15.4,   1. ],
        [  3. , -15. , -15. , -15. ,   1. ],
        [  4. , -19.3, -19.3, -19.3,   1. ],
        [  5. , -16.8, -16.8, -16.8,   1. ],
        [  6. , -11.4, -11.4, -11.4,   1. ],
        [  7. ,  -7.6,  -7.6,  -7.6,   1. ],
        [  8. ,  -7.1,  -7.1,  -7.1,   1. ],
        [  9. , -10.1, -10.1, -10.1,   1. ],
        [ 10. ,  -9.5,  -9.5,  -9.5,   1. ]]),
 array([[  1. ,  -6.1,  -6.1,  -6.1,   1. ],
        [  2. , -15.4, -15.4, -15.4,   1. ],
        [  3. , -15. , -15. , -15. ,   1. ],
        [  4. , -19.3, -19.3, -19.3,   1. ],
        [  5. , -16.8, -16.8, -16.8,   1. ],
        [  6. , -11.4, -11.4, -11.4,   1. ],
        [  7. ,  -7.6,  -7.6,  -7.6,   1. ],
        [  8. ,  -7.1,  -7.1,  -7.1,   1. ],
        [  9. , -10.1, -10.1, -10.1,   1. ],
        [ 10. ,  -9.5,  -9.5,  -9.5,   1. ]]))

Opětovné uložení

In [114]:
numpy.savetxt("ascii_data_1_new.txt", data1, fmt="%6g")     # uložíme pod jiným jménem
print(open("ascii_data_1_new.txt", "r").read())             # přesvědčíme se

     1   -6.1   -6.1   -6.1      1
     2  -15.4  -15.4  -15.4      1
     3    -15    -15    -15      1
     4  -19.3  -19.3  -19.3      1
     5  -16.8  -16.8  -16.8      1
     6  -11.4  -11.4  -11.4      1
     7   -7.6   -7.6   -7.6      1
     8   -7.1   -7.1   -7.1      1
     9  -10.1  -10.1  -10.1      1
    10   -9.5   -9.5   -9.5      1



Je možné používat i vlastní NumPy formát, příkazy jsou stejné bez txt (save, load)

## Srovnání rychlosti

#### Součet vektorů

In [ ]:
import time
import numpy as np

velikostVektoru = 100000

def SoucetSeznamy():
    t1 = time.time()
    X = range(velikostVektoru)
    Y = range(velikostVektoru)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - t1

def SoucetNumPy():
    t1 = time.time()
    X = np.arange(velikostVektoru)
    Y = np.arange(velikostVektoru)
    Z = X + Y
    return time.time() - t1


t1 = SoucetSeznamy()
t2 = SoucetNumPy()
print(t1, t2)
print("Numpy je zde " + str(t1/t2) + " rychlejší!")

0.036014556884765625 0.0010023117065429688
Numpy je zde 35.931493815413894 rychlejší!


#### Násobení vektorů

Klasicky (bez NumPy)

In [8]:
from time import process_time
mez = 100000
opak = 100

def nasobeni(l1, l2):
    dot = 0
    for i, j in zip(l1, l2):        # zip prochází oba seznamy a vezme odpovídající záznamy (se stejným indexem)
        dot += i*j
    #dot2 = 0
    #for i in range(mez):
    #    dot2 += l1[i]*l2[i]
    return dot


list1 = list(range(mez))            # čísla od 0 až do mez-1
list2 = list(range(mez))

start = process_time()              # začátek měření času
for i in range(opak):
    dot = nasobeni(list1, list2)
end = process_time()                # konec měření času

print(dot)
print(type(dot))
round(end - start, 10)

333328333350000
<class 'int'>


0.890625

Pomocí NumPy

In [77]:
import numpy
from time import process_time
opak = 100
arr1 = numpy.arange(mez, dtype=numpy.int64)
arr2 = numpy.arange(mez, dtype=numpy.int64)

start = process_time()              # začátek měření času
for i in range(opak):
    dot = arr1 @ arr2
    #dot = numpy.dot(arr1, arr2)
end = process_time()                # konec měření času

print(dot)
print(type(dot))
round(end - start, 10)

333332833333500000
<class 'numpy.int64'>


0.25

#### Výpočet funkčních hodnot

Klasicky (bez NumPy)

In [18]:
import math
mez = 1000000

list1 = list(range(mez))
list2=[0]*mez
print(list1[:20])
print(list2[:20])
start = process_time()
for i in range(len(list2)):
    list2[i]=math.sin(list1[i])
print(list2[:10])
end = process_time()
round(end - start, 10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0.0, 0.8414709848078965, 0.9092974268256817, 0.1411200080598672, -0.7568024953079282, -0.9589242746631385, -0.27941549819892586, 0.6569865987187891, 0.9893582466233818, 0.4121184852417566]


0.296875

Pomocí NumPy

In [25]:
arr1 = numpy.arange(mez, dtype=numpy.int64)
print(arr1[:20])
start = process_time()
arr2 = numpy.sin(arr1)
print(arr2[:10])
print(format(arr2[1],'.16f'))
end = process_time()
round(end - start, 10)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
0.8414709848078965


0.03125

#### Mazání

Klasicky (bez NumPy)

In [82]:
list1 = list(range(mez))
start = process_time()
del list1
end = process_time()
round(end - start, 10)

0.015625

Pomocí NumPy

In [83]:
arr1 = numpy.arange(mez, dtype=numpy.int64)
start = process_time()
del arr1
end = process_time()
round(end - start, 10)

0.0

## Lineární algebra s numpy.linalg
Základní operace, doplněno v SciPy

Několik příkladů:

In [85]:
import numpy
a = numpy.array([[1, 2], [3, 4]])           # array
print(a)
print(type(a))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


Výpočet determinantu

In [ ]:
a = numpy.array([[1, 2], [3, 4]])
numpy.linalg.det(a)

-2.0000000000000004

Výpočet hodnosti matice

In [87]:
from numpy.linalg import matrix_rank
print(a)
print("Hodnost a:", matrix_rank(a))
print("Hodnost jednotkové 4x4:", matrix_rank(numpy.eye(4)))

[[1 2]
 [3 4]]
Hodnost a: 2
Hodnost jednotkové 4x4: 4


In [89]:
I=numpy.eye(4)
I[-1,-1] = 0                # odstraníme poslední diag. hodnotu
matrix_rank(I)              # hodnost je menší

3

Stopa matice

In [91]:
numpy.trace(numpy.eye(3))   # součet prvků na diagonále

3.0

In [26]:
a = numpy.arange(8).reshape((2,2,2))        # 2×2×2
print(a)
numpy.trace(a)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([6, 8])

Inverze matice

In [97]:
from numpy.linalg import inv
a = numpy.array([[1., 2.], [3., 4.]])
ainv = inv(a)           # inverzní
print(a)
print(ainv)
print(a @ ainv)         # kontrola
numpy.allclose(a @ ainv, numpy.eye(2))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


True

## Třída Matice
pohodlné, ale nepřináší nic nového

In [ ]:
A = numpy.mat('[1 2;3 4]')
A

matrix([[1, 2],
        [3, 4]])

Transpozice, inverze

In [ ]:
A.T, A.I

(matrix([[1, 3],
         [2, 4]]),
 matrix([[-2. ,  1. ],
         [ 1.5, -0.5]]))

Násobení matic a vektorů

In [ ]:
b = numpy.mat('[5 6]')
b*A, A*b.T

(matrix([[23, 34]]),
 matrix([[17],
         [39]]))

https://numpy.org/devdocs/reference/routines.linalg.html