## NumPy

Základní vědecká a analytická knihovna pro vědecké výpočty a manipulaci s daty

- n-rozměrné homogenní pole
- API pro práci s ním
    - efektivnější operace

Instalace

In [2]:
!python -m pip install numpy

V případě potřeby aktualizace Pip Package Installer

In [3]:
!python -m pip install --upgrade pip

## Datové typy

In [1]:
import sys, numpy, math
a = math.sqrt(2)
print(a, type(a), sys.getsizeof(a))

b = numpy.sqrt(2)                       # nebo b = numpy.double(numpy.sqrt(2))
print(b, type(b), sys.getsizeof(b))

c = numpy.longdouble(numpy.sqrt(2))
print(c, type(c), sys.getsizeof(c))

1.4142135623730951 <class 'float'> 24
1.4142135623730951 <class 'numpy.float64'> 32
1.4142135623730951 <class 'numpy.longdouble'> 32


## Definice polí

Numpy pole 
- pole hodnot
- všechny stejného typu
- indexováno n-ticí nezáporných celých čísel

Seznam 
- pythonovský ekvivalent pole
- lze měnit jeho velikost
- může obsahovat prvky různých typů

Výhody NumPy pole
- menší velikost v paměti
- vyšší výkon
- optimalizované funkce (lineární algebra)

In [3]:
import numpy
vector = numpy.array([1, 2, 3, 4])                      # vektor int
a1 = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # pole 3 × 3
vector, a1

(array([1, 2, 3, 4]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

Srovnání se seznamem (list)

In [6]:
seznam = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]          # seznam (list)
seznam

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Možnost převést seznam na pole

In [7]:
a1 = numpy.array(seznam)
print(a1)
print(seznam)
# velikosti
print("Pole:", sys.getsizeof(a1))
print("Seznam:", sys.getsizeof(seznam))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Pole: 164
Seznam: 80


Velikost menší pro větší seznamy

In [8]:
seznam = list(range(100))
a1 = numpy.array(seznam)
print("Pole:", sys.getsizeof(a1))
print("Seznam:", sys.getsizeof(seznam))

Pole: 512
Seznam: 856


#### Vlastnosti pole
- tvar (velikost) pole - shape (např. matice 3×3)
- datový typ pole - shape (typ prvků)

In [9]:
a1 = numpy.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])             # pole 3 × 3
print(a1.shape)          # tvar (-> n-tice)
print(sys.getsizeof(a1)) # velikost
a1.dtype                 # typ

(3, 3)
164


dtype('int32')

In [25]:
a1 = numpy.array([
    [1, 2, 3.0],
    [4, 5, 6],
    [7, 8, 9]])             # pole 3 × 3
print(a1.shape)          # tvar (-> n-tice)
print(sys.getsizeof(a1)) # velikost
a1.dtype      

(3, 3)
200


dtype('float64')

Pole větších řádů

In [11]:
krychle = numpy.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(krychle.shape)
krychle

(2, 2, 2)


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## Základní operace
- probíhá po všech prvcích

In [26]:
a1 = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # pole 3 × 3
a1                                                   # výpis pole

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Přičtení skalární hodnoty

In [13]:
a1 - 1, - a1

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[-1, -2, -3],
        [-4, -5, -6],
        [-7, -8, -9]]))

Násobení skalární hodnotou

In [14]:
a1 * 2, a1 / 2

(array([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]),
 array([[0.5, 1. , 1.5],
        [2. , 2.5, 3. ],
        [3.5, 4. , 4.5]]))

Celočíselné dělení

In [15]:
a1 // 2, a1 % 2

(array([[0, 1, 1],
        [2, 2, 3],
        [3, 4, 4]], dtype=int32),
 array([[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]], dtype=int32))

Porovnání

In [16]:
a1 > 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

Logické spojení operací přes bitové operátory & (a) a | (nebo)
- neintuitivní priorita (nutno závorkovat)
- (Python neumožňuje předefinovat chování operátorů and a or)

In [17]:
(a1 > 3) & (a1 < 7)

array([[False, False, False],
       [ True,  True,  True],
       [False, False, False]])

## Operace s dalšími poli
opět po prvcích

definujeme druhé pole

In [27]:
a1 = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # pole 3 × 3
a2 = numpy.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]])
a1, a2              # výpis obou polí

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[0, 1, 0],
        [1, 0, 1],
        [0, 1, 0]]))

Sčítání polí

In [19]:
a1 + a2

array([[1, 3, 3],
       [5, 5, 7],
       [7, 9, 9]])

Násobení (po prvcích)
- neodpovídá maticovému násobení

In [20]:
a1 * a2

array([[0, 2, 0],
       [4, 0, 6],
       [0, 8, 0]])

Seznam převeden na pole automaticky

In [28]:
seznam = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]          # seznam (list)
print(seznam)
a1 * seznam

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

## Indexování, výběr

In [6]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Pole se chová jako sekvence menších polí
- 1. řádek

In [23]:
a1[0]            # 1. řádek

array([1, 2, 3])

- poslední řádek

In [24]:
a1[-1]           # poslední řádek

array([7, 8, 9])

- rozsah

In [25]:
a1[:-1]          # 1. až předposlední

array([[1, 2, 3],
       [4, 5, 6]])

- prvek

In [26]:
a1[0][1]         # 1. řádek, 2. sloupec

2

- přístup k prvku v NumPy lze i pomocí n-tice

In [7]:
a1[0, 1]         # 1. řádek, 2. sloupec

2

In [28]:
a1[:-1, 1:]      # 1. až předposlední řádek, od 2. sloupce

array([[2, 3],
       [5, 6]])

Výběr řádku a sloupce
- pomocí ":"

In [29]:
display(a1[2])
a1[2, :]     # 3. řádek (totéž jako a1[2])

array([7, 8, 9])

array([7, 8, 9])

In [30]:
a1[:, 2]     # 3. sloupec

array([3, 6, 9])

Pozor na editaci!
- jedná se o stejné pole

In [44]:
a1 = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # pole 3 × 3
v = a1[1, :]        # 2. řádek (totéž jako a1[1])
display(v)
v[-1] = 0           # editujeme vektor
a1                  # ovlivní to matici

array([4, 5, 6])

array([[1, 2, 3],
       [4, 5, 0],
       [7, 8, 9]])

odkaz na původní objekt, ze kterého bylo pole vytvořeno

In [55]:
display(v.base)         # array([[1.,0.],[3.,4.]])
print(v.base is a1)     # True
print(a1.copy().base)   # kopie nemá vztah k pův. objektu

array([[1, 2, 3],
       [4, 5, 0],
       [7, 8, 9]])

True
None


Výběr prvků pomocí pole logických hodnot

In [30]:
display(a1)
vetsi = a1 > 4          # vpravo matice, obsahuje True a False
display(vetsi)          # pole logických hodnot
a1[vetsi]               # pole prvků

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

array([5, 6, 7, 8, 9])

Změna pořadí řádků a sloupců, kopie řádků a sloupců

In [31]:
display(a1[1])          # 2. řádek
display(a1[[1]])        # pole obsahující 2. řádek
a1[[0, 2, 1, 1]]        # řádky 0, 2, 1 a 1 (pole obsahující tyto řádky)

array([4, 5, 6])

array([[4, 5, 6]])

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6],
       [4, 5, 6]])

In [33]:
a1[:, [2, 2, 0, 0]]      # sloupce 2, 2, 0, 0

array([[3, 3, 1, 1],
       [6, 6, 4, 4],
       [9, 9, 7, 7]])

## Operace s různě velkými poli
- odpovídající dimenze se "rozšíří" (jako u skaláru) - broadcasting

Přičtení vektoru

In [38]:
b = numpy.array([1, 0, 10])       # (stejné velikosti)
display(a1)
display(b)
display(a1 + b)

c = numpy.array([1, 0])           # (jiné velikosti) - chyba
b + c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([ 1,  0, 10])

array([[ 2,  2, 13],
       [ 5,  5, 16],
       [ 8,  8, 19]])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [11]:
print("Původní:\n", a1)
print("Přičtení řádkového vektoru:\n", a1 + [1, 0, 10])
print("Násobení řádkovým vektorem:\n", a1 * [1, 0, 10])
print("Násobení sloupcovým vektorem:\n", a1 * [[1], [0], [10]])

Původní:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Přičtení řádkového vektoru:
 [[ 2  2 13]
 [ 5  5 16]
 [ 8  8 19]]
Násobení řádkovým vektorem:
 [[ 1  0 30]
 [ 4  0 60]
 [ 7  0 90]]
Násobení sloupcovým vektorem:
 [[ 1  2  3]
 [ 0  0  0]
 [70 80 90]]


## Editace polí

In [ ]:
a1[0, 0] = 100               # jedna z možností
a1[1][1] = 200               # jiný způsob
a1

array([[100,   2,   3],
       [  4, 200,   6],
       [  7,   8,   9]])

lze měnit jakýkoliv výběr, funguje rozšiřování (broadcasting)

In [ ]:
a1[0] = 100          # první řádek
print(a1)
a1[:, 1] = 500       # druhý sloupec
print(a1)
a1[:] = 100          # všechny prvky
a1

[[100 100 100]
 [  4 200   6]
 [  7   8   9]]
[[100 500 100]
 [  4 500   6]
 [  7 500   9]]


array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

Editace rozšířeným přiřazením

In [ ]:
a1 *= 2
a1

array([[200, 200, 200],
       [200, 200, 200],
       [200, 200, 200]])

Operace array = array * 2 dává stejný výsledek, ale vytvoří nové pole, které pak přiřadí do původní proměnné

## Tvoření matic pomocí funkcí

Naplnění matice m × n libovolným stejným číslem

In [ ]:
numpy.full((4, 4), 3.14)                    # tvar, hodnota

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

Naplnění matice m × n nulami (jedničkami)

In [ ]:
numpy.zeros((4, 4)), numpy.ones((4, 4))     # nuly, jedničky

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

Jednotková a diagonální matice (vždy čtvercové)

In [ ]:
numpy.eye(4), numpy.diag([1, 2, 3, 4])     # dimenze, prvky diagonály

(array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 array([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]]))

Vždy lze specifikovat datový typ

In [ ]:
int_zeros = numpy.zeros((4, 4), dtype='int8')
print(int_zeros.dtype)
int_zeros

int8


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

### Jednorozměrná pole

arange
- začátek, konec, přírůstek
- pod. jako range()

In [ ]:
print(numpy.arange(20))             # 0 až 19
print(numpy.arange(4, 20, 2))       # od, do, přírůstek

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 4  6  8 10 12 14 16 18]


Jdou i reálná čísla, ale pozor na chyby

In [ ]:
numpy.arange(0.0, 20.0, 0.3)[-1]

19.8

linspace
- pro reálná čísla vhodnější - rovnoměrné dělení
- začátek a konec intervalu plus počet prvků

In [ ]:
numpy.linspace(0, 20, num=30)

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

## Změna tvaru pole

In [13]:
a1 = numpy.arange(12)            # výchozí pole
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

reshape
- musí odpovídat velikost

In [ ]:
a2 = a1.reshape((3, 4))         # řádky, sloupce
a3 = a1.reshape((4, 3))
a2, a3

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

- nahradíme-li jedno z čísel -1, dopočítá se 

In [16]:
a2 = a1.reshape((-1, 4))         # řádky, sloupce
a3 = a1.reshape((4, 3))
a3 = a1.reshape((-1, 3))
a2, a3

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [23]:
C = numpy.arange(2).reshape(-1,1)   # sloupec 0,1
R = numpy.arange(2).reshape(1,-1)   # řádek 0,1
display(C)
display(R)
C + R                               # broadcasting



array([[0],
       [1]])

array([[0, 1]])

array([[0, 1],
       [1, 2]])

Pozor na editaci!
- jedná se o stejné pole

In [ ]:
a2[2,2] = 100               # 3. řádek, 3. sloupec (pův. 10)
a2, a1, a3               # editovalo se jen a2

(array([[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9, 100,  11]]),
 array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100,  11]),
 array([[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9, 100,  11]]))

Pro kopii dat copy

In [ ]:
a2 = a1.reshape((3, 4)).copy()
a2[2, 2] = 10
a2, a3

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9, 100,  11]]))

Transpozice

In [ ]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

Skládání polí - stacking (concatenate)

In [16]:
arr1 = numpy.arange(1,10).reshape(3,3)
arr2 = 2*arr1
print(arr1)
print(arr2)

# horizontální skládání
arr3=numpy.hstack((arr1, arr2))
print(arr3)
arr4=numpy.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]
[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]


In [20]:
# vertikální skládání
arr5=numpy.vstack((arr1, arr2))
print(arr5)
arr6=numpy.concatenate((arr1, arr2), axis=0)
print(arr6)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [24]:
arr1 = numpy.arange(1,10).reshape(3,3)
arr2 = 2*arr1
print(arr1)
print(arr2)

# složení přes osu z (depth)
arr7=numpy.dstack((arr1, arr2))
arr7

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])

In [39]:
arr1 = numpy.arange(4,7) 
arr2 = 2 * arr1
print(arr1)
print(arr2)
print()

# column stack
arr_col_stack = numpy.column_stack((arr1,arr2))
print(arr_col_stack)
print(numpy.hstack((arr1.T,arr2.T)))    # transpozice nemá vliv na 1D pole

# row stack
arr_row_stack = numpy.row_stack((arr1,arr2)) 
print(arr_row_stack)
print(numpy.vstack((arr1,arr2)))


[4 5 6]
[ 8 10 12]

[[ 4  8]
 [ 5 10]
 [ 6 12]]
[ 4  5  6  8 10 12]
[[ 4  5  6]
 [ 8 10 12]]
[[ 4  5  6]
 [ 8 10 12]]


In [45]:
arr=numpy.arange(1,10).reshape(3,3)
print(arr)

# vodorovné dělení (na sloupce)
numpy.hsplit(arr, 3)    # nebo numpy.split(arr,3,axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [48]:
# svislé dělení (na řádky)
numpy.vsplit(arr, 3)    # nebo numpy.split(arr,3,axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

## Datové typy

In [ ]:
print(numpy.zeros(4, dtype=int))        # pro matici (4,4)
print(numpy.zeros(4, dtype=float))
print(numpy.zeros(4, dtype=bool))

[0 0 0 0]
[0. 0. 0. 0.]
[False False False False]


Změna datového typu

In [52]:
arr=numpy.arange(1,10).reshape(3,3)
print(arr)

arr=arr.astype(float)
print(arr)
print("Změněný typ:", arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Změněný typ: float64


Pokud uložíme různé datové typy, výsledkem je defaultně string 

(zde little-endian 32 character string)

In [ ]:
numpy.array([0, 3.14, "ahoj"])

array(['0', '3.14', 'ahoj'], dtype='<U32')

Nejobecnější typ je object

In [ ]:
numpy.array([0, 3.14, "ahoj"], dtype=object)

array([0, 3.14, 'ahoj'], dtype=object)

Další možnosti: Klasické řetězcové specifikace, bytestring (ukončeny \0), složené datové typy (records)

## Maticové násobení
- původně funkce dot, od Pythonu 3.5 operátor @ (mATrix multiplication),

Násobení matice vektorem

In [6]:
array1 = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = numpy.array([1, 0, 0])
array1 @ vector, numpy.dot(array1, vector), array1.dot(vector)

(array([1, 4, 7]), array([1, 4, 7]), array([1, 4, 7]))

Násobení dvou matic

In [4]:
array1 = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = numpy.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]])
array1 @ array2, numpy.dot(array1, array2), array1.dot(array2)

(array([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]]),
 array([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]]),
 array([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]]))

Neodpovídající rozměry

In [7]:
array1 = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = numpy.array([1, 0, 0])
vector @ array1                         # automatická transpozice

array([1, 2, 3])

In [8]:
array1 = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = numpy.array([1, 0])            # pouze 2 hodnoty - chyba
vector @ array1

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

## Booleovské hodnoty polí

In [ ]:
E = numpy.eye(3)
if E.any():                         # obsahuje cokoliv nenulového
    print('Alespoň jeden prvek je nenulový')
if E.all():                         # všechny prvky nenulové
    print('Všechny prvky jsou nenulové')
print(E.size)
if E.size:                          # počet prvků
    print('Pole obsahuje nějaké prvky')

Alespoň jeden prvek je nenulový
9
Pole obsahuje nějaké prvky


## Aplikace funkcí
např. vytvoříme hodnoty z intervalu 0 až $\pi$ s dělením na 1000 dílků a spočítáme sinus 

In [ ]:
#                     od,       do,   dělení   
a1 = numpy.linspace(0, numpy.pi, num=1000)   # vytvoření pole
a1[:10]                                      # výpis prvních 10 prvků

array([0.        , 0.00314474, 0.00628947, 0.00943421, 0.01257895,
       0.01572369, 0.01886842, 0.02201316, 0.0251579 , 0.02830264])

In [ ]:
sinus = numpy.sin(a1)                        # použití funkce sin
sinus[:10]                                      # výpis prvních 10 prvků

array([0.        , 0.00314473, 0.00628943, 0.00943407, 0.01257862,
       0.01572304, 0.0188673 , 0.02201138, 0.02515525, 0.02829886])

## Práce se soubory
Nejdříve vytvoříme textový soubor s daty
- writefile (file) - magický příkaz, vytvoří soubor a zapíše do něj to, co následuje

In [ ]:
%%writefile ascii_data_1.txt         
 1    -6.1    -6.1    -6.1 1
 2   -15.4   -15.4   -15.4 1
 3   -15.0   -15.0   -15.0 1
 4   -19.3   -19.3   -19.3 1
 5   -16.8   -16.8   -16.8 1
 6   -11.4   -11.4   -11.4 1
 7    -7.6    -7.6    -7.6 1
 8    -7.1    -7.1    -7.1 1
 9   -10.1   -10.1   -10.1 1
10    -9.5    -9.5    -9.5 1

Overwriting ascii_data_1.txt


Pokusíme se načíst data ze souboru

In [ ]:
data1 = numpy.genfromtxt('ascii_data_1.txt')
data2 = numpy.loadtxt('ascii_data_1.txt')
#print(data1 == data2)
data1, data2

(array([[  1. ,  -6.1,  -6.1,  -6.1,   1. ],
        [  2. , -15.4, -15.4, -15.4,   1. ],
        [  3. , -15. , -15. , -15. ,   1. ],
        [  4. , -19.3, -19.3, -19.3,   1. ],
        [  5. , -16.8, -16.8, -16.8,   1. ],
        [  6. , -11.4, -11.4, -11.4,   1. ],
        [  7. ,  -7.6,  -7.6,  -7.6,   1. ],
        [  8. ,  -7.1,  -7.1,  -7.1,   1. ],
        [  9. , -10.1, -10.1, -10.1,   1. ],
        [ 10. ,  -9.5,  -9.5,  -9.5,   1. ]]),
 array([[  1. ,  -6.1,  -6.1,  -6.1,   1. ],
        [  2. , -15.4, -15.4, -15.4,   1. ],
        [  3. , -15. , -15. , -15. ,   1. ],
        [  4. , -19.3, -19.3, -19.3,   1. ],
        [  5. , -16.8, -16.8, -16.8,   1. ],
        [  6. , -11.4, -11.4, -11.4,   1. ],
        [  7. ,  -7.6,  -7.6,  -7.6,   1. ],
        [  8. ,  -7.1,  -7.1,  -7.1,   1. ],
        [  9. , -10.1, -10.1, -10.1,   1. ],
        [ 10. ,  -9.5,  -9.5,  -9.5,   1. ]]))

Opětovné uložení

In [ ]:
numpy.savetxt("ascii_data_1_new.txt", data1, fmt="%6g")     # uložíme pod jiným jménem
print(open("ascii_data_1_new.txt", "r").read())             # přesvědčíme se

     1   -6.1   -6.1   -6.1      1
     2  -15.4  -15.4  -15.4      1
     3    -15    -15    -15      1
     4  -19.3  -19.3  -19.3      1
     5  -16.8  -16.8  -16.8      1
     6  -11.4  -11.4  -11.4      1
     7   -7.6   -7.6   -7.6      1
     8   -7.1   -7.1   -7.1      1
     9  -10.1  -10.1  -10.1      1
    10   -9.5   -9.5   -9.5      1



Je možné používat i vlastní NumPy formát, příkazy jsou stejné bez txt (save, load)

## Srovnání rychlosti

#### Součet vektorů

In [30]:
import time
import numpy as np

velikostVektoru = 1000000

def SoucetSeznamy1():                   # klasické for
    t1 = time.time()
    X = range(velikostVektoru)
    Y = range(velikostVektoru)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1

def SoucetSeznamy():
    t1 = time.time()
    X = range(velikostVektoru)
    Y = range(velikostVektoru)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - t1

def SoucetNumPy():                      # numpy
    t1 = time.time()
    X = np.arange(velikostVektoru)
    Y = np.arange(velikostVektoru)
    Z = X + Y
    return time.time() - t1

print(SoucetSeznamy1())
t1 = SoucetSeznamy()
t2 = SoucetNumPy()
print(t1)
print(t2)
if t2 != 0:
    print("Numpy je rychlejší {:.2f}×".format(t1/t2))
else:
    print("Podíl nelze stanovit")

0.3661055564880371
0.28478312492370605
0.004105329513549805
Numpy je rychlejší 69.37×


#### Násobení vektorů

Klasicky (bez NumPy)

In [ ]:
from time import process_time
mez = 100000
opak = 100

def nasobeni(l1, l2):
    dot = 0
    for i, j in zip(l1, l2):        # zip prochází oba seznamy a vezme odpovídající záznamy (se stejným indexem)
        dot += i*j
    #dot2 = 0
    #for i in range(mez):
    #    dot2 += l1[i]*l2[i]
    return dot


list1 = list(range(mez))            # čísla od 0 až do mez-1
list2 = list(range(mez))

start = process_time()              # začátek měření času
for i in range(opak):
    dot = nasobeni(list1, list2)
end = process_time()                # konec měření času

print(dot)
print(type(dot))
round(end - start, 10)

333328333350000
<class 'int'>


0.890625

Pomocí NumPy

In [33]:
import numpy
from time import process_time
opak = 100
arr1 = numpy.arange(mez, dtype=numpy.int64)
arr2 = numpy.arange(mez, dtype=numpy.int64)

start = process_time()              # začátek měření času
for i in range(opak):
    dot = arr1 @ arr2
    #dot = numpy.dot(arr1, arr2)
end = process_time()                # konec měření času

print(dot)
print(type(dot))
round(end - start, 10)

333332833333500000
<class 'numpy.int64'>


0.25

#### Výpočet funkčních hodnot

Klasicky (bez NumPy)

In [39]:
import math
mez = 1000000

list1 = list(range(mez))
list2=[0]*mez               # zatím samé nuly
print(list1[:20])

start = process_time()
for i in range(len(list2)):
    list2[i]=math.sin(list1[i])
print(list2[:10])
end = process_time()
print("čas:", round(end - start, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0.0, 0.8414709848078965, 0.9092974268256817, 0.1411200080598672, -0.7568024953079282, -0.9589242746631385, -0.27941549819892586, 0.6569865987187891, 0.9893582466233818, 0.4121184852417566]
čas: 0.28125


Pomocí NumPy

In [38]:
arr1 = numpy.arange(mez, dtype=numpy.int64)
print(arr1[:20])

start = process_time()
arr2 = numpy.sin(arr1)
print(arr2[:10])                    # výpis v kompaktnější formě
print(format(arr2[1],'.16f'))       # přesnost stejná
end = process_time()
print("čas:", round(end - start, 10))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
0.8414709848078965
čas: 0.015625


In [67]:

def my_func(x):
    y = x**3 - 2*x + 5
    if y>0.5:
        return y-0.5
    else:
        return 0

v =  range(100000)

t1 = process_time()
a1 = [my_func(vk) for vk in v]
t2 = process_time()
a2 = np.vectorize(my_func)(v)
t3 = process_time()
print("for:", t2-t1)
print("np:", t3-t2)

for: 0.0625
np: 0.09375


#### Mazání

Klasicky (bez NumPy)

In [ ]:
list1 = list(range(mez))
start = process_time()
del list1
end = process_time()
round(end - start, 10)

0.015625

Pomocí NumPy

In [ ]:
arr1 = numpy.arange(mez, dtype=numpy.int64)
start = process_time()
del arr1
end = process_time()
round(end - start, 10)

0.0

## Lineární algebra s numpy.linalg
Základní operace, doplněno v SciPy

Několik příkladů:

In [ ]:
import numpy
a = numpy.array([[1, 2], [3, 4]])           # a1
print(a)
print(type(a))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


Výpočet determinantu

In [ ]:
a = numpy.array([[1, 2], [3, 4]])
numpy.linalg.det(a)

-2.0000000000000004

Výpočet hodnosti matice

In [ ]:
from numpy.linalg import matrix_rank
print(a)
print("Hodnost a:", matrix_rank(a))
print("Hodnost jednotkové 4x4:", matrix_rank(numpy.eye(4)))

[[1 2]
 [3 4]]
Hodnost a: 2
Hodnost jednotkové 4x4: 4


In [ ]:
I=numpy.eye(4)
I[-1,-1] = 0                # odstraníme poslední diag. hodnotu
matrix_rank(I)              # hodnost je menší

3

Stopa matice

In [ ]:
numpy.trace(numpy.eye(3))   # součet prvků na diagonále

3.0

In [ ]:
a = numpy.arange(8).reshape((2,2,2))        # 2×2×2
print(a)
numpy.trace(a)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([6, 8])

Inverze matice

In [ ]:
from numpy.linalg import inv
a = numpy.array([[1., 2.], [3., 4.]])
ainv = inv(a)           # inverzní
print(a)
print(ainv)
print(a @ ainv)         # kontrola
numpy.allclose(a @ ainv, numpy.eye(2))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


True

## Třída Matice
pohodlné, ale nepřináší nic nového

In [ ]:
A = numpy.mat('[1 2;3 4]')
A

matrix([[1, 2],
        [3, 4]])

Transpozice, inverze

In [ ]:
A.T, A.I

(matrix([[1, 3],
         [2, 4]]),
 matrix([[-2. ,  1. ],
         [ 1.5, -0.5]]))

Násobení matic a vektorů

In [ ]:
b = numpy.mat('[5 6]')
b*A, A*b.T

(matrix([[23, 34]]),
 matrix([[17],
         [39]]))

https://numpy.org/devdocs/reference/routines.linalg.html