# Matematický software 

## Cv. 4 - Lineární algebra


In [ ]:
!python -m pip install numpy

In [ ]:
!python -m pip install scipy

In [ ]:
#pro apple silicon architektury
!python -m pip install --pre -i https://pypi.anaconda.org/scipy-wheels-nightly/simple scipy

#### CACv.4.1: Reprezentace vektoru

In [30]:
import numpy as np

#naivni zpusob
a = [1, 3, 2]
b = [4, 2, 1]
soucin = [a[i] * b[i] for i in range(min(len(a), len(b)))]
print("soucet:", soucin)

#numpy
a = np.array([1, 3, 2])
b = np.array([4, 2, 1])
soucin = a * b
print("soucet:", soucin)

soucet: [4, 6, 2]
soucet: [4 6 2]


#### CACv.4.2: Práce se vektory

In [18]:
# skalovani vektoru
alfa = 0.5
a = np.array([1, 3, 2])
print(alfa*a)

[0.5 1.5 1. ]


In [19]:
# sčítání vektorů
a = np.array([1, 3, 2])
b = np.array([4, 2, 1])
print(a+b)

[5 5 3]


In [20]:
# násobení složek vektorů
a = np.array([1, 3, 2])
b = np.array([4, 2, 1])
print(a*b)

[4 6 2]


In [21]:
# podíl složek vektorů
a = np.array([1, 3, 2])
b = np.array([4, 2, 1])
print(a/b)

[0.25 1.5  2.  ]


In [22]:
#generovani ekvidistantniho vektoru
zacatek = 4
konec = 16
inkrement = 2
ekvidistantni_vektor = np.arange(zacatek, konec, inkrement)
print(ekvidistantni_vektor)

[ 4  6  8 10 12 14]


In [23]:
#generovani nahodneho vektoru celych cisel
nahodny_vektor = np.random.randint(1, 5, size=10)
print(nahodny_vektor)


[1 2 3 4 3 4 1 3 3 4]


In [24]:
#generovani nahodneho vektoru desetinnych cisel
nahodny_vektor = np.random.random(10)
print(nahodny_vektor)

[0.13578582 0.64965204 0.70468478 0.65228311 0.4179311  0.00881883
 0.85957151 0.30829163 0.45637437 0.20782546]


In [25]:
#generovani nahodneho vektoru ze standardniho rozdeleni
nahodny_vektor = np.random.randn(100)
stredni_hodnota = nahodny_vektor.mean()
smerodatna_odchylka = nahodny_vektor.std()
print("mean: ", stredni_hodnota, "stdev:", smerodatna_odchylka)

mean:  -0.07298123453100545 stdev: 1.00770767446078


#### CACv.4.3: Skalární součin


<img src="MS4_soubory/skalarni_soucin.png" alt="Drawing" style="width: 550px;"/>

In [26]:
a = np.array([1, 3, 2])
b = np.array([4, 2, 1])

skalarni_soucin = np.dot(a, b)
print(skalarni_soucin)
a.dot(b), a @ b

12


(12, 12)

In [27]:
#velikost vektoru pomoci skalarniho soucinu
a = np.array([1, 3, 2])

velikost = np.sqrt(a.dot(a))
print(velikost)

velikost = np.linalg.norm(a)
print(velikost)

3.7416573867739413
3.7416573867739413


#### CACv.4.4: Vektorový součin


<img src="MS4_soubory/vektorovy_soucin.png" alt="Drawing" style="width: 600px;"/>

In [28]:
a = np.array([1, 3, 2])
b = np.array([4, 2, 1])

vektorovy_soucin = np.cross(a, b)
print(vektorovy_soucin)

[ -1   7 -10]


#### CACv.4.5: Tenzorový součin


<img src="MS4_soubory/tenzorovy_soucin.png" alt="Drawing" style="width: 600px;"/>

In [29]:
a = np.array([1, 3, 2])
b = np.array([4, 2, 1])

tenzorovy_soucin = np.tensordot(a, b, axes=0)
print(tenzorovy_soucin)

[[ 4  2  1]
 [12  6  3]
 [ 8  4  2]]


#### CACv.4.6: Práce s maticí

In [30]:
#standardni zpusob vytvareni matic
matice = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])
print(matice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
#matice plna jednicek
nradku = 4
nsloupcu = 3
matice_jednicky = np.ones((nradku, nsloupcu))
print(matice_jednicky)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [32]:
#matice plna nul
nradku = 4
nsloupcu = 3
matice_nuly = np.zeros((nradku, nsloupcu))
print(matice_nuly)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
#matice plna libovolne hodnoty
nradku = 4
nsloupcu = 3
matice = np.full((nradku, nsloupcu), 5, dtype='float')
print(matice)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [34]:
#zmena tvaru matice
matice = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
])
stary_tvar = matice.shape
stara_velikost = matice.size
print("tvar: ", stary_tvar, "velikost: ", stara_velikost, "\n", matice)

matice = matice.reshape(2, 6) #nebo matice.reshape(-1, 6), -1 znamena, ze dopocita pocet prvku v dimenzi za nas
novy_tvar = matice.shape
nova_velikost = matice.size
print("tvar: ", novy_tvar, "velikost: ", nova_velikost, "\n", matice)

tvar:  (3, 4) velikost:  12 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
tvar:  (2, 6) velikost:  12 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [35]:
#zplosteni matice
matice = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
])
stary_tvar = matice.shape
stara_velikost = matice.size
print("tvar: ", stary_tvar, "velikost: ", stara_velikost, "\n", matice)

matice = matice.flatten()
novy_tvar = matice.shape
nova_velikost = matice.size
print("tvar: ", novy_tvar, "velikost: ", nova_velikost, "\n", matice)

tvar:  (3, 4) velikost:  12 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
tvar:  (12,) velikost:  12 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [36]:
#rozdil mezi flatten a ravel
matice = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
])

vektor_flatten = matice.flatten() #vraci kopii
vektor_ravel = matice.ravel() #vraci jen jiny pohled na matici (zmeny v matici a vektoru jsou provazany v pameti)

matice[0][0] = 13

print(vektor_flatten)
print(vektor_ravel)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[13  2  3  4  5  6  7  8  9 10 11 12]


#### CACv.4.7: Násobení matic

In [37]:
A = np.array([
    [1, 2], 
    [3, 4], 
    [5, 6]
])

B = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

C = np.matmul(A, B)
print("A shape:",A.shape,"B shape: ", B.shape,"C shape: ", C.shape)
print(C)

A shape: (3, 2) B shape:  (2, 3) C shape:  (3, 3)
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


#### CACv.4.8: Hodnost matice

In [38]:
matice = np.array([
    [1, 2, 1], 
    [1, 1, 1], 
    [2, 2, 3]
])

hodnost = np.linalg.matrix_rank(matice)
print(hodnost)

3


In [39]:
matice = np.array([
    [1, 2, 1], 
    [1, 1, 1], 
    [2, 2, 2]
])
hodnost = np.linalg.matrix_rank(matice)
print(hodnost)

2


#### CACv.4.7: Stopa matice

<img src="MS4_soubory/stopa.png" alt="Drawing" style="width: 600px;"/>

In [40]:
matice = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
])

stopa_matice = matice.trace()
print(stopa_matice)

matice = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8]
])

15


#### CACv.4.10: Transpozice matice


In [41]:
matice = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8]
])

transponovana_matice = matice.transpose()
print(transponovana_matice)
matice.T

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

#### CACv.4.11: Inverzní matice

<img src="MS4_soubory/inverzni_matice.png" alt="Drawing" style="width: 600px;"/>

In [42]:
A = np.array([
    [1, 2, -1], 
    [2, 0, 1],
    [1, -2, 1]
])

In [43]:
#jednotkova matice
E = np.eye(3)
print(E)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
#inverzni matice
X = np.linalg.inv(A)
print(X)

[[ 0.5   0.    0.5 ]
 [-0.25  0.5  -0.75]
 [-1.    1.   -1.  ]]


In [45]:
#kontrola
print(np.matmul(A, X))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### CACv.4.12: Determinant

<img src="MS4_soubory/determinant.png" alt="Drawing" style="width: 600px;"/>

In [46]:
A = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
])

det = np.linalg.det(A)
print(det)

0.0


#### CACv.4.13: Cramerovo pravidlo

<img src="MS4_soubory/cramerovo_pravidlo.png" alt="Drawing" style="width: 500px;"/>

<img src="MS4_soubory/priklad_cramer.png" alt="Drawing" style="width: 500px;"/>

Odbočka
- chceme vyjádřit vektory obsahující v jednotlivých sloupcích jedničky

In [47]:
print(np.diag([1,1,1]))                                 # vytvoření jednotkové matice
krychle = np.broadcast_to(np.diag([1,1,1]), [3,3,3])    # rozšíření na matici 3x3x3 (vektor 3 jednotkových matic)
print(krychle)
# představíme si jako krychli; při přehození os můžeme mít sloupcové vektory jedniček a nul
krychle.swapaxes(0, 2), krychle.swapaxes(0, 1)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[[1 0 0]
  [0 1 0]
  [0 0 1]]

 [[1 0 0]
  [0 1 0]
  [0 0 1]]

 [[1 0 0]
  [0 1 0]
  [0 0 1]]]


(array([[[1, 1, 1],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [1, 1, 1],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [1, 1, 1]]]),
 array([[[1, 0, 0],
         [1, 0, 0],
         [1, 0, 0]],
 
        [[0, 1, 0],
         [0, 1, 0],
         [0, 1, 0]],
 
        [[0, 0, 1],
         [0, 0, 1],
         [0, 0, 1]]]))

In [48]:
mask = np.broadcast_to(np.diag([1,1,1]), [3, 3, 3]).swapaxes(0, 1)
print(mask)

[[[1 0 0]
  [1 0 0]
  [1 0 0]]

 [[0 1 0]
  [0 1 0]
  [0 1 0]]

 [[0 0 1]
  [0 0 1]
  [0 0 1]]]


In [49]:
A = np.array([                          # matice soustavy
    [3, 2, 1], 
    [2, 3, 1],
    [2, 1, 3]
])
b = np.array([5, 1, 11])                # vektor pravých stran

n = A.shape[1]                          # počet sloupců

# nejdříve vytvoříme matici rozšířením vektoru pravých stran 
print(np.repeat(b, n))                  # opakuje jednotlivé prvky vektoru b (3x)
print(np.repeat(b, n).reshape(n, n))
print(np.broadcast_to(b, [n, n]).T)     # jiný postup

# zkombinujeme obě matice podle podmínky (masky)
Ai = np.where(mask, np.repeat(b, n).reshape(n, n), A)   # Ai = np.where(mask, vektb3x3, A)
print(Ai)

[ 5  5  5  1  1  1 11 11 11]
[[ 5  5  5]
 [ 1  1  1]
 [11 11 11]]
[[ 5  5  5]
 [ 1  1  1]
 [11 11 11]]
[[[ 5  2  1]
  [ 1  3  1]
  [11  1  3]]

 [[ 3  5  1]
  [ 2  1  1]
  [ 2 11  3]]

 [[ 3  2  5]
  [ 2  3  1]
  [ 2  1 11]]]


In [50]:
x = np.linalg.det(Ai) / np.linalg.det(A)
print(x)

[ 2. -2.  3.]


#### CACv.4.14: Gaussova eliminační metoda
Jediná příma iterační metoda v modulech pythonu je LU dekompozice, což je komplikovanější verze Gaussovy eliminační metody. Více na kurzu numerické matematiky.


In [34]:
#LU dekompozice - zakladni metoda linalg.solve
A = np.array([
    [2, 1], 
    [5, 7]
])
b = np.array([11, 13])

x = np.linalg.solve(A, b)
print(x)

[ 7.11111111 -3.22222222]


#### CACv.4.15: Iterační metody

In [32]:
A = np.array([
    [3, 2, 1], 
    [2, 3, 1],
    [2, 1, 3]
])

In [53]:
D = np.diag(A)
print(D)

[3 3 3]


In [54]:
L = np.tril(A)
print(L)

[[3 0 0]
 [2 3 0]
 [2 1 3]]


In [55]:
L = np.tril(A, k = -1)
print(L)

[[0 0 0]
 [2 0 0]
 [2 1 0]]


In [56]:
U = np.triu(A, k = 1)
print(U)

[[0 2 1]
 [0 0 1]
 [0 0 0]]


Jacobiho metoda: 

<img src="MS4_soubory/jacobi_iterace.png" alt="Drawing" style="width: 300px;"/>

In [35]:
def jacobi(A, b, niteraci, x0=np.ones(len(A))):
    x = x0
    D = np.diag(A)
    L = np.tril(A, k = -1)
    U = np.triu(A, k = 1)
    for i in range(niteraci):
        x = (b - np.matmul((L + U),x))/D
        print("iterace:",i, "x=",x)
    return x

A = np.array([
    [2, 1], 
    [5, 7]
])
b = np.array([11, 13])

x = jacobi(A, b, 20)
print("reseni: ", x)

iterace: 0 x= [5.         1.14285714]
iterace: 1 x= [ 4.92857143 -1.71428571]
iterace: 2 x= [ 6.35714286 -1.66326531]
iterace: 3 x= [ 6.33163265 -2.68367347]
iterace: 4 x= [ 6.84183673 -2.6654519 ]
iterace: 5 x= [ 6.83272595 -3.02988338]
iterace: 6 x= [ 7.01494169 -3.02337568]
iterace: 7 x= [ 7.01168784 -3.15352978]
iterace: 8 x= [ 7.07676489 -3.1512056 ]
iterace: 9 x= [ 7.0756028  -3.19768921]
iterace: 10 x= [ 7.0988446  -3.19685914]
iterace: 11 x= [ 7.09842957 -3.21346043]
iterace: 12 x= [ 7.10673022 -3.21316398]
iterace: 13 x= [ 7.10658199 -3.21909301]
iterace: 14 x= [ 7.10954651 -3.21898714]
iterace: 15 x= [ 7.10949357 -3.22110465]
iterace: 16 x= [ 7.11055232 -3.22106683]
iterace: 17 x= [ 7.11053342 -3.22182309]
iterace: 18 x= [ 7.11091154 -3.22180958]
iterace: 19 x= [ 7.11090479 -3.22207967]
reseni:  [ 7.11090479 -3.22207967]


Gaussovo-Seidelova metoda: 

<img src="MS4_soubory/gauss_seidel_iterace.png" alt="Drawing" style="width: 300px;"/>

In [36]:
def gauss_seidel(A, b, niteraci, x0=np.ones(len(A))):
    x = x0
    U = np.triu(A, k = 1)
    Lstar = np.tril(A, k = 0)               #D + L
    T = np.matmul(-np.linalg.inv(Lstar), U) #T = -invL* . U
    C = np.matmul(np.linalg.inv(Lstar), b)  #C = invL . b
    for i in range(niteraci):
        x = np.matmul(T, x) + C             #inv(D+L).(b-U.x) = inv(Lstar).(b-U.x) = C + T => x = Tx + C
        print("iterace:",i, "x=",x)
    return x

A = np.array([
    [16, 3], 
    [7, -11]
])
b = np.array([11, 13])

x = gauss_seidel(A, b, 20)
print(x)

iterace: 0 x= [ 0.5        -0.86363636]
iterace: 1 x= [ 0.84943182 -0.64127066]
iterace: 2 x= [ 0.80773825 -0.66780293]
iterace: 3 x= [ 0.81271305 -0.66463715]
iterace: 4 x= [ 0.81211947 -0.66501489]
iterace: 5 x= [ 0.81219029 -0.66496981]
iterace: 6 x= [ 0.81218184 -0.66497519]
iterace: 7 x= [ 0.81218285 -0.66497455]
iterace: 8 x= [ 0.81218273 -0.66497463]
iterace: 9 x= [ 0.81218274 -0.66497462]
iterace: 10 x= [ 0.81218274 -0.66497462]
iterace: 11 x= [ 0.81218274 -0.66497462]
iterace: 12 x= [ 0.81218274 -0.66497462]
iterace: 13 x= [ 0.81218274 -0.66497462]
iterace: 14 x= [ 0.81218274 -0.66497462]
iterace: 15 x= [ 0.81218274 -0.66497462]
iterace: 16 x= [ 0.81218274 -0.66497462]
iterace: 17 x= [ 0.81218274 -0.66497462]
iterace: 18 x= [ 0.81218274 -0.66497462]
iterace: 19 x= [ 0.81218274 -0.66497462]
[ 0.81218274 -0.66497462]


SOR metoda: 

<img src="MS4_soubory/sor_iterace.png" alt="Drawing" style="width: 300px;"/>

In [37]:
def sor(A, b, omega, niteraci, x0=np.ones(len(A))):
    x = x0
    U = np.triu(A, k = 1)
    Lstar = np.tril(A, k = 0)               
    T = np.matmul(-np.linalg.inv(Lstar), U) 
    C = np.matmul(np.linalg.inv(Lstar), b)  
    for i in range(niteraci):
        Fx = np.matmul(T, x) + C
        delta_x = Fx - x
        x = x + omega*delta_x
        print("iterace:",i, "x=",x)
    return x


A = np.array([
    [16, 3], 
    [7, -11]
])
b = np.array([11, 13])

x = gauss_seidel(A, b, 10, np.ones(len(A)))
print(x)

iterace: 0 x= [ 0.5        -0.86363636]
iterace: 1 x= [ 0.84943182 -0.64127066]
iterace: 2 x= [ 0.80773825 -0.66780293]
iterace: 3 x= [ 0.81271305 -0.66463715]
iterace: 4 x= [ 0.81211947 -0.66501489]
iterace: 5 x= [ 0.81219029 -0.66496981]
iterace: 6 x= [ 0.81218184 -0.66497519]
iterace: 7 x= [ 0.81218285 -0.66497455]
iterace: 8 x= [ 0.81218273 -0.66497463]
iterace: 9 x= [ 0.81218274 -0.66497462]
[ 0.81218274 -0.66497462]


#### CACv.4.16: Symbolická matematika a matice

In [ ]:
!python -m pip install sympy

In [1]:
import sympy

In [ ]:
#reprezentace matic v sympy
A = sympy.Matrix([
    [1, -1],
    [3, 4]
])
A

Matrix([
[1, -1],
[3,  4]])

In [ ]:
#specialni matice
D = sympy.diag(1,2,3)
D

Matrix([
[1, 0, 0],
[0, 2, 0],
[0, 0, 3]])

In [ ]:
#operace nad matici
A = sympy.Matrix([
    [1, -1],
    [3, 4]
])
A**-1

Matrix([
[ 4/7, 1/7],
[-3/7, 1/7]])

In [ ]:
#transpozice
A = sympy.Matrix([
    [1, -1],
    [3, 4],
    [0, 2]
])
A.T

Matrix([
[ 1, 3, 0],
[-1, 4, 2]])

In [66]:
#vlozeni vektoru do matice
A = sympy.Matrix([
    [1, -1],
    [3, 4],
    [0, 2]
])
v = sympy.Matrix([[10, 10]])
A = A.row_insert(1, v)
A

Matrix([
[ 1, -1],
[10, 10],
[ 3,  4],
[ 0,  2]])

In [65]:
#determinant
A = sympy.Matrix([
    [1, -1],
    [3, 4],
])
A.det()

7

In [27]:
#diagonalizace - vrací n-tici P, D, kde D je diagonální a A = P.D.P-1
A = sympy.Matrix([
    [0, 1, 1],
    [1, 1, 1],
    [1, 1, 0],
])
P, D = A.diagonalize()
B = P*D*P**-1
sympy.pprint(P)
sympy.pprint(D)         # diagonální
print(B)                # má být původní
sympy.simplify(B)       # po zjednodušení je původní

⎡-1   1   1 ⎤
⎢           ⎥
⎢0   -√2  √2⎥
⎢           ⎥
⎣1    1   1 ⎦
⎡-1    0       0   ⎤
⎢                  ⎥
⎢0   1 - √2    0   ⎥
⎢                  ⎥
⎣0     0     1 + √2⎦
Matrix([[0, -sqrt(2)*(1 - sqrt(2))/4 + sqrt(2)*(1 + sqrt(2))/4, 1], [-sqrt(2)*(1 - sqrt(2))/4 + sqrt(2)*(1 + sqrt(2))/4, 1, -sqrt(2)*(1 - sqrt(2))/4 + sqrt(2)*(1 + sqrt(2))/4], [1, -sqrt(2)*(1 - sqrt(2))/4 + sqrt(2)*(1 + sqrt(2))/4, 0]])


⎡0  1  1⎤
⎢       ⎥
⎢1  1  1⎥
⎢       ⎥
⎣1  1  0⎦

In [28]:
#diagonalizace (4x4)
A = sympy.Matrix([
    [0, 1, 1, 0],
    [1, 1, 1, -1],
    [1, 1, 1, 0],
    [1, 1, 0, 1]
])
print(A.diagonalize())
A.diagonalize()             # totéž, grafický výstup

(Matrix([
[ 1,    (-sqrt(3) - 13*2**(1/3)*I*(7 + 21*sqrt(3)*I)**(2/3)/18 - 2*sqrt(3)*98**(1/3)*(1 + 3*sqrt(3)*I)**(2/3)/9 - 5*2**(2/3)*sqrt(3)*(7 + 21*sqrt(3)*I)**(1/3)/6 - 2**(2/3)*I*(7 + 21*sqrt(3)*I)**(1/3)/2 + 2*98**(1/3)*I*(1 + 3*sqrt(3)*I)**(2/3)/9 + 5*I + 7*2**(1/3)*sqrt(3)*(7 + 21*sqrt(3)*I)**(2/3)/18)/(sqrt(3) - 5*I), (-3*sqrt(3) - 7*2**(1/3)*sqrt(3)*(7 + 21*sqrt(3)*I)**(2/3)/18 - 2*2**(2/3)*sqrt(3)*(7 + 21*sqrt(3)*I)**(1/3)/3 - 2*98**(1/3)*I*(1 + 3*sqrt(3)*I)**(2/3)/9 + I + 2*sqrt(3)*98**(1/3)*(1 + 3*sqrt(3)*I)**(2/3)/9 + 2**(2/3)*I*(7 + 21*sqrt(3)*I)**(1/3) + 13*2**(1/3)*I*(7 + 21*sqrt(3)*I)**(2/3)/18)/(3*sqrt(3) - I),     1 + 7/(3*(7/54 + 7*sqrt(3)*I/18)**(1/3)) - (2/3 + 7/(9*(7/54 + 7*sqrt(3)*I/18)**(1/3)) + (7/54 + 7*sqrt(3)*I/18)**(1/3))**2 + 3*(7/54 + 7*sqrt(3)*I/18)**(1/3)],
[-1, (2*sqrt(3)/3 - 2*2**(1/3)*sqrt(3)*(7 + 21*sqrt(3)*I)**(2/3)/9 - 10*I/3 - 2*98**(1/3)*I*(1 + 3*sqrt(3)*I)**(2/3)/9 + 2**(2/3)*sqrt(3)*(7 + 21*sqrt(3)*I)**(1/3)/3 + 2*2**(2/3)*I*(7 + 21*sqrt(3)*

⎛                                                                             
⎜⎡             3 ___                2/3        3 ____             2/3      2/3
⎜⎢          13⋅╲╱ 2 ⋅ⅈ⋅(7 + 21⋅√3⋅ⅈ)      2⋅√3⋅╲╱ 98 ⋅(1 + 3⋅√3⋅ⅈ)      5⋅2   
⎜⎢    -√3 - ─────────────────────────── - ─────────────────────────── - ──────
⎜⎢                       18                            9                      
⎜⎢1   ────────────────────────────────────────────────────────────────────────
⎜⎢                                                                            
⎜⎢                                                                            
⎜⎢                                                                            
⎜⎢                                                                            
⎜⎢                                                                            
⎜⎢             3 ___                 2/3            3 ____               2/3  
⎜⎢    2⋅√3   2⋅╲╱ 2 ⋅√3⋅(7 + 21⋅√3⋅ⅈ)      10⋅ⅈ   2⋅

### Samostatná cvičení

#### SCv.4.1: Levi-Cituv symbol

<img src="MS4_soubory/levicit.png" alt="Drawing" style="width: 600px;"/>

#### SCv.4.2: Laplaceův rozvoj

<img src="MS4_soubory/laplace.png" alt="Drawing" style="width: 600px;"/>

<img src="MS4_soubory/laplace2.png" alt="Drawing" style="width: 600px;"/>

#### SCv.4.3: Cramerovo pravidlo

<img src="MS4_soubory/cramer_priklad.png" alt="Drawing" style="width: 600px;"/>

In [ ]:
def cramer2(A, b):
    Ai = np.array([np.copy(A), np.copy(A), np.copy(A)])
    for i in range(len(A)):
        Ai[i][:,i] = b
    x = np.linalg.det(Ai) / np.linalg.det(A)
    return x

A = np.array([
    [3, 2, 1], 
    [2, 3, 1],
    [2, 1, 3]
])
b = np.array([5, 1, 11])
print(cramer2(A, b))

[ 2. -2.  3.]


In [ ]:
def cramer(A, b):
    N = A.shape[1]
    mask = np.broadcast_to(np.diag([1,1,1]), [N, N, N]).swapaxes(0, 1)
    Ai = np.where(mask, np.repeat(b, N).reshape(N, N), A)
    print("mask:\n", mask)
    print("A:\n", A)
    print("Ai:\n", Ai)
    x = np.linalg.det(Ai) / np.linalg.det(A)
    return x

A = np.array([
    [3, 2, 1], 
    [2, 3, 1],
    [2, 1, 3]
])
b = np.array([5, 1, 11])
print(cramer(A, b))

mask:
 [[[1 0 0]
  [1 0 0]
  [1 0 0]]

 [[0 1 0]
  [0 1 0]
  [0 1 0]]

 [[0 0 1]
  [0 0 1]
  [0 0 1]]]
A:
 [[3 2 1]
 [2 3 1]
 [2 1 3]]
Ai:
 [[[ 5  2  1]
  [ 1  3  1]
  [11  1  3]]

 [[ 3  5  1]
  [ 2  1  1]
  [ 2 11  3]]

 [[ 3  2  5]
  [ 2  3  1]
  [ 2  1 11]]]
[ 2. -2.  3.]


#### SCv.4.4: Jacobiho metoda

<img src="MS4_soubory/jacobi_priklad.png" alt="Drawing" style="width: 600px;"/>

In [70]:
import numpy as np
def jacobi(A, b, niteraci, x0=np.ones(len(A))):
    x = x0
    D = np.diag(A)
    L = np.tril(A, k = -1)
    U = np.triu(A, k = 1)
    for i in range(niteraci):
        x = (b - np.matmul((L + U),x))/D    # inverzní matice diagonální je diagonální a má převrácené hodnoty
        print("iterace:",i, "x=",x)
    return x

A = np.array([
    [6, 2, -3], 
    [1, 4, -2],
    [3, 2, -7]
])
b = np.array([10, 6, -4])

x = jacobi(A, b, 10)
print("reseni: ", x)

iterace: 0 x= [1.83333333 1.75       1.28571429]
iterace: 1 x= [1.72619048 1.68452381 1.85714286]
iterace: 2 x= [2.03373016 1.99702381 1.79251701]
iterace: 3 x= [1.89725057 1.88782596 2.01360544]
iterace: 4 x= [2.04419407 2.03249008 1.9239148 ]
iterace: 5 x= [1.95112738 1.95090889 2.02822319]
iterace: 6 x= [2.0304753  2.02632975 1.96502856]
iterace: 7 x= [1.97373769 1.97489545 2.02058363]
iterace: 8 x= [2.01866    2.01685739 1.981572  ]
iterace: 9 x= [1.98516687 1.986121   2.01281354]
reseni:  [1.98516687 1.986121   2.01281354]
