# Matematický software 

## Cv. 4 - Lineární algebra

Prezentace: [POSEL](MS4_soubory/LinearniAlgebra.pdf)

### Cognitive Apprenticeship

V tomto cvičení ...

In [ ]:
!python3 -m pip install numpy

In [ ]:
!python3 -m pip install scipy

In [ ]:
#pro apple silicon architektury
!python3 -m pip install --pre -i https://pypi.anaconda.org/scipy-wheels-nightly/simple scipy

#### CACv.4.1: Reprezentace vektoru

In [ ]:
import numpy as np

#naivni zpusob
a = [1, 3, 2]
b = [4, 2, 1]
soucin = [a[i] * b[i] for i in range(min(len(a), len(b)))]
print("soucet:", soucin)

#numpy
a = np.array([1, 3, 2])
b = np.array([4, 2, 1])
soucin = a * b
print("soucet:", soucin)

#### CACv.4.2: Práce se vektory

In [189]:
#skalovani vektoru
alfa = 0.5
a = np.array([1, 3, 2])
print(alfa*a)

[0.5 1.5 1. ]


In [190]:
#scitani vektoru
a = np.array([1, 3, 2])
b = np.array([4, 2, 1])
print(a+b)

[5 5 3]


In [191]:
#nasobeni vektoru
a = np.array([1, 3, 2])
b = np.array([4, 2, 1])
print(a*b)

[4 6 2]


In [192]:
#podil vektoru
a = np.array([1, 3, 2])
b = np.array([4, 2, 1])
print(a/b)

[0.25 1.5  2.  ]


In [31]:
#generovani ekvidistantniho vektoru
zacatek = 4
konec = 16
inkrement = 2
ekvidistantni_vektor = np.arange(zacatek, konec, inkrement)
print(ekvidistantni_vektor)

[ 4  6  8 10 12 14]


In [18]:
#generovani nahodneho vektoru celych cisel
nahodny_vektor = np.random.randint(1, 5, size=10)
print(nahodny_vektor)


[4 2 1 2 2 3 1 1 3 4]


In [19]:
#generovani nahodneho vektoru desetinnych cisel
nahodny_vektor = np.random.random(10)
print(nahodny_vektor)

[0.39662322 0.25540082 0.25291494 0.25545713 0.24512366 0.77734024
 0.85077822 0.95744373 0.86647489 0.4001942 ]


In [20]:
#generovani nahodneho vektoru ze standardniho rozdeleni
nahodny_vektor = np.random.randn(100)
stredni_hodnota = nahodny_vektor.mean()
smerodatna_odchylka = nahodny_vektor.std()
print("mean: ", stredni_hodnota, "stdev:", smerodatna_odchylka)

mean:  -0.07969162474874708 stdev: 1.055598692741235


#### CACv.4.3: Skalární součin

Lorem

<img src="MS4_soubory/skalarni_soucin.png" alt="Drawing" style="width: 550px;"/>

In [51]:
a = np.array([1, 3, 2])
b = np.array([4, 2, 1])

skalarni_soucin = np.dot(a, b)
print(skalarni_soucin)

12


In [195]:
#velikost vektoru pomoci skalarniho soucinu
a = np.array([1, 3, 2])

velikost = np.sqrt(a.dot(a))
print(velikost)

velikost = np.linalg.norm(a)
print(velikost)

3.7416573867739413
3.7416573867739413


#### CACv.4.4: Vektorový součin

Lorem

<img src="MS4_soubory/vektorovy_soucin.png" alt="Drawing" style="width: 600px;"/>

In [188]:
a = np.array([1, 3, 2])
b = np.array([4, 2, 1])

vektorovy_soucin = np.cross(a, b)
print(vektorovy_soucin)

[ -1   7 -10]


#### CACv.4.5: Tenzorový součin

Lorem

<img src="MS4_soubory/tenzorovy_soucin.png" alt="Drawing" style="width: 600px;"/>

In [184]:
a = np.array([1, 3, 2])
b = np.array([4, 2, 1])

tenzorovy_soucin = np.tensordot(a, b, axes=0)
print(tenzorovy_soucin)

[[ 4  2  1]
 [12  6  3]
 [ 8  4  2]]


#### CACv.4.6: Práce s maticí

In [ ]:
#standardni zpusob vytvareni matic
matice = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])
print(matice)

In [ ]:
#matice plna jednicek
nradku = 4
nsloupcu = 3
matice_jednicky = np.ones((nradku, nsloupcu))
print(matice_jednicky)

In [ ]:
#matice plna nul
nradku = 4
nsloupcu = 3
matice_nuly = np.zeros((nradku, nsloupcu))
print(matice_nuly)

In [ ]:
#matice plna libovolne hodnoty
nradku = 4
nsloupcu = 3
matice = np.full((nradku, nsloupcu), 5, dtype='float')
print(matice)

In [39]:
#zmena tvaru matice
matice = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
])
stary_tvar = matice.shape
stara_velikost = matice.size
print("tvar: ", stary_tvar, "velikost: ", stara_velikost, "\n", matice)

matice = matice.reshape(2, 6) #nebo matice.reshape(-1, 6), -1 znamena, ze dopocita pocet prvku v dimenzi za nas
novy_tvar = matice.shape
nova_velikost = matice.size
print("tvar: ", novy_tvar, "velikost: ", nova_velikost, "\n", matice)

tvar:  (3, 4) velikost:  12 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
tvar:  (2, 6) velikost:  12 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [41]:
#zplosteni matice
matice = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
])
stary_tvar = matice.shape
stara_velikost = matice.size
print("tvar: ", stary_tvar, "velikost: ", stara_velikost, "\n", matice)

matice = matice.flatten()
novy_tvar = matice.shape
nova_velikost = matice.size
print("tvar: ", novy_tvar, "velikost: ", nova_velikost, "\n", matice)

tvar:  (3, 4) velikost:  12 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
tvar:  (12,) velikost:  12 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [42]:
#rozdil mezi flatten a ravel
matice = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
])

vektor_flatten = matice.flatten() #vraci kopii
vektor_ravel = matice.ravel() #vraci jen jiny pohled na matici (zmeny v matici a vektoru jsou provazany v pameti)

matice[0][0] = 13

print(vektor_flatten)
print(vektor_ravel)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[13  2  3  4  5  6  7  8  9 10 11 12]


#### CACv.4.7: Násobení matic

In [49]:
A = np.array([
    [1, 2], 
    [3, 4], 
    [5, 6]
])

B = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

C = np.matmul(A, B)
print("A shape:",A.shape,"B shape: ", B.shape,"C shape: ", C.shape)
print(C)

A shape: (3, 2) B shape:  (2, 3) C shape:  (3, 3)
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


#### CACv.4.8: Hodnost matice

In [106]:
matice = np.array([
    [1, 2, 1], 
    [1, 1, 1], 
    [2, 2, 3]
])

hodnost = np.linalg.matrix_rank(matice)
print(hodnost)

3


In [107]:
matice = np.array([
    [1, 2, 1], 
    [1, 1, 1], 
    [2, 2, 2]
])
hodnost = np.linalg.matrix_rank(matice)
print(hodnost)

2


#### CACv.4.7: Stopa matice

<img src="MS4_soubory/stopa.png" alt="Drawing" style="width: 600px;"/>

In [46]:
matice = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
])

stopa_matice = matice.trace()
print(stopa_matice)

matice = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8]
])

15


#### CACv.4.10: Transpozice matice


In [44]:
matice = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8]
])

transponovana_matice = matice.transpose()
print(transponovana_matice)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


#### CACv.4.11: Inverzní matice

<img src="MS4_soubory/inverzni_matice.png" alt="Drawing" style="width: 600px;"/>

In [96]:
A = np.array([
    [1, 2, -1], 
    [2, 0, 1],
    [1, -2, 1]
])

In [97]:
#jednotkova matice
E = np.eye(3)
print(E)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [98]:
#inverzni matice
X = np.linalg.inv(A)
print(X)

[[ 0.5   0.    0.5 ]
 [-0.25  0.5  -0.75]
 [-1.    1.   -1.  ]]


In [99]:
#kontrola
print(np.matmul(A, X))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### CACv.4.12: Determinant

<img src="MS4_soubory/determinant.png" alt="Drawing" style="width: 600px;"/>

In [56]:
A = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
])

det = np.linalg.det(A)
print(det)

-9.51619735392994e-16


#### CACv.4.13: Cramerovo pravidlo

<img src="MS4_soubory/cramerovo_pravidlo.png" alt="Drawing" style="width: 500px;"/>

<img src="MS4_soubory/priklad_cramer.png" alt="Drawing" style="width: 500px;"/>

In [ ]:
mask = np.broadcast_to(np.diag([1,1,1]), [3, 3, 3]).swapaxes(0, 1)
print(mask)

In [ ]:
A = np.array([
    [3, 2, 1], 
    [2, 3, 1],
    [2, 1, 3]
])
b = np.array([5, 1, 11])

pocet_sloupcu = A.shape[1]

Ai = np.where(mask, np.repeat(b, pocet_sloupcu).reshape(pocet_sloupcu, pocet_sloupcu), A)
print(Ai)

In [89]:
x = np.linalg.det(Ai) / np.linalg.det(A)
print(x)

[ 2. -2.  3.]


#### CACv.4.14: Gaussova eliminační metoda
Jediná příma iterační metoda v modulech pythonu je LU dekompozice, což je komplikovanější verze Gaussovy eliminační metody. Více na kurzu numerické matematiky.


In [161]:
#LU dekompozice - zakladni metoda linalg.solve
A = np.array([
    [2, 1], 
    [5, 7]
])
b = np.array([11, 13])

x = np.linalg.solve(A, b)
print(x)

[ 7.11111111 -3.22222222]


#### CACv.4.15: Iterační metody

In [109]:
A = np.array([
    [3, 2, 1], 
    [2, 3, 1],
    [2, 1, 3]
])

In [110]:
D = np.diag(A)
print(D)

[3 3 3]


In [111]:
L = np.tril(A)
print(L)

[[3 0 0]
 [2 3 0]
 [2 1 3]]


In [112]:
L = np.tril(A, k = -1)
print(L)

[[0 0 0]
 [2 0 0]
 [2 1 0]]


In [113]:
U = np.triu(A, k = 1)
print(U)

[[0 2 1]
 [0 0 1]
 [0 0 0]]


Jacobiho metoda: 

<img src="MS4_soubory/jacobi_iterace.png" alt="Drawing" style="width: 300px;"/>

In [175]:
def jacobi(A, b, niteraci, x0=np.ones(len(A))):
    x = x0
    D = np.diag(A)
    L = np.tril(A, k = -1)
    U = np.triu(A, k = 1)
    for i in range(niteraci):
        x = (b - np.matmul((L + U),x))/D
        print("iterace:",i, "x=",x)
    return x

A = np.array([
    [2, 1], 
    [5, 7]
])
b = np.array([11, 13])

x = jacobi(A, b, 10)
print("reseni: ", x)

iterace: 0 x= [5.         1.14285714]
iterace: 1 x= [ 4.92857143 -1.71428571]
iterace: 2 x= [ 6.35714286 -1.66326531]
iterace: 3 x= [ 6.33163265 -2.68367347]
iterace: 4 x= [ 6.84183673 -2.6654519 ]
iterace: 5 x= [ 6.83272595 -3.02988338]
iterace: 6 x= [ 7.01494169 -3.02337568]
iterace: 7 x= [ 7.01168784 -3.15352978]
iterace: 8 x= [ 7.07676489 -3.1512056 ]
iterace: 9 x= [ 7.0756028  -3.19768921]
reseni:  [ 7.0756028  -3.19768921]


Gaussovo-Seidelova metoda: 

<img src="MS4_soubory/gauss_seidel_iterace.png" alt="Drawing" style="width: 300px;"/>

In [176]:
def gauss_seidel(A, b, niteraci, x0=np.ones(len(A))):
    x = x0
    U = np.triu(A, k = 1)
    Lstar = np.tril(A, k = 0)               #D + L
    T = np.matmul(-np.linalg.inv(Lstar), U) #T = -invL* . U
    C = np.matmul(np.linalg.inv(Lstar), b)  #C = invL . b
    for i in range(niteraci):
        x = np.matmul(T, x) + C             #inv(D+L).(b-U.x) = inv(Lstar).(b-U.x) = C + T => x = Tx + C
        print("iterace:",i, "x=",x)
    return x

A = np.array([
    [16, 3], 
    [7, -11]
])
b = np.array([11, 13])

x = gauss_seidel(A, b, 10)
print(x)

iterace: 0 x= [ 0.5        -0.86363636]
iterace: 1 x= [ 0.84943182 -0.64127066]
iterace: 2 x= [ 0.80773825 -0.66780293]
iterace: 3 x= [ 0.81271305 -0.66463715]
iterace: 4 x= [ 0.81211947 -0.66501489]
iterace: 5 x= [ 0.81219029 -0.66496981]
iterace: 6 x= [ 0.81218184 -0.66497519]
iterace: 7 x= [ 0.81218285 -0.66497455]
iterace: 8 x= [ 0.81218273 -0.66497463]
iterace: 9 x= [ 0.81218274 -0.66497462]
[ 0.81218274 -0.66497462]


SOR metoda: 

<img src="MS4_soubory/sor_iterace.png" alt="Drawing" style="width: 300px;"/>

In [177]:
def sor(A, b, omega, niteraci, x0=np.ones(len(A))):
    x = x0
    U = np.triu(A, k = 1)
    Lstar = np.tril(A, k = 0)               
    T = np.matmul(-np.linalg.inv(Lstar), U) 
    C = np.matmul(np.linalg.inv(Lstar), b)  
    for i in range(niteraci):
        Fx = np.matmul(T, x) + C
        delta_x = Fx - x
        x = x + omega*delta_x
        print("iterace:",i, "x=",x)
    return x


A = np.array([
    [16, 3], 
    [7, -11]
])
b = np.array([11, 13])

x = gauss_seidel(A, b, 10, np.ones(len(A)))
print(x)

iterace: 0 x= [ 0.5        -0.86363636]
iterace: 1 x= [ 0.84943182 -0.64127066]
iterace: 2 x= [ 0.80773825 -0.66780293]
iterace: 3 x= [ 0.81271305 -0.66463715]
iterace: 4 x= [ 0.81211947 -0.66501489]
iterace: 5 x= [ 0.81219029 -0.66496981]
iterace: 6 x= [ 0.81218184 -0.66497519]
iterace: 7 x= [ 0.81218285 -0.66497455]
iterace: 8 x= [ 0.81218273 -0.66497463]
iterace: 9 x= [ 0.81218274 -0.66497462]
[ 0.81218274 -0.66497462]


#### CACv.4.16: Symbolická matematika a matice

In [ ]:
!python3 -m pip install sympy

In [196]:
import sympy

In [209]:
#reprezentace matic v sympy
A = sympy.Matrix([
    [1, -1],
    [3, 4]
])
A

Matrix([
[ 4/7, 1/7],
[-3/7, 1/7]])

In [213]:
#specialni matice
D = sympy.diag(1,2,3)
D

Matrix([
[1, 0, 0],
[0, 2, 0],
[0, 0, 3]])

In [214]:
#operace nad matici
A = sympy.Matrix([
    [1, -1],
    [3, 4]
])
A**-1

Matrix([
[ 4/7, 1/7],
[-3/7, 1/7]])

In [211]:
#transpozice
A = sympy.Matrix([
    [1, -1],
    [3, 4],
    [0, 2]
])
A.T

Matrix([
[ 1, 3, 0],
[-1, 4, 2]])

In [208]:
#vlozeni vektoru do matice
A = sympy.Matrix([
    [1, -1],
    [3, 4],
    [0, 2]
])
v = sympy.Matrix([[10, 10]])
A = A.row_insert(1, v)
A

Matrix([
[ 1, -1],
[10, 10],
[ 3,  4],
[ 0,  2]])

In [216]:
#determinant
A = sympy.Matrix([
    [1, -1],
    [3, 4],
])
A.det()

7

In [217]:
#diagonalizace
A = sympy.Matrix([
    [0, 1, 1, 0],
    [1, 1, 1, -1],
    [1, 1, 1, 0],
    [1, 1, 0, 1]
])
A.diagonalize()

(Matrix([
 [-1/2 - sqrt(3)*I/6, -1/2 + sqrt(3)*I/6],
 [                 1,                  1]]),
 Matrix([
 [5/2 - sqrt(3)*I/2,                 0],
 [                0, 5/2 + sqrt(3)*I/2]]))

### Samostatná cvičení

#### SCv.4.1: Levi-Cituv symbol

<img src="MS4_soubory/levicit.png" alt="Drawing" style="width: 600px;"/>

#### SCv.4.2: Laplaceův rozvoj

<img src="MS4_soubory/laplace.png" alt="Drawing" style="width: 600px;"/>

<img src="MS4_soubory/laplace2.png" alt="Drawing" style="width: 600px;"/>

#### SCv.4.3: Cramerovo pravidlo

<img src="MS4_soubory/cramer_priklad.png" alt="Drawing" style="width: 600px;"/>

In [183]:
def cramer(A, b):
    N = A.shape[1]
    mask = np.broadcast_to(np.diag([1,1,1]), [N, N, N]).swapaxes(0, 1)
    Ai = np.where(mask, np.repeat(b, N).reshape(N, N), A)
    x = np.linalg.det(Ai) / np.linalg.det(A)
    return x

A = np.array([
    [3, 2, 1], 
    [2, 3, 1],
    [2, 1, 3]
])
b = np.array([5, 1, 11])
print(cramer(A, b))

[ 2. -2.  3.]


#### SCv.4.4: Jacobiho metoda

<img src="MS4_soubory/jacobi_priklad.png" alt="Drawing" style="width: 600px;"/>

In [182]:
def jacobi(A, b, niteraci, x0=np.ones(len(A))):
    x = x0
    D = np.diag(A)
    L = np.tril(A, k = -1)
    U = np.triu(A, k = 1)
    for i in range(niteraci):
        x = (b - np.matmul((L + U),x))/D
        print("iterace:",i, "x=",x)
    return x

A = np.array([
    [6, 2, -3], 
    [1, 4, -2],
    [3, 2, -7]
])
b = np.array([10, 6, -4])

x = jacobi(A, b, 100)
print("reseni: ", x)

iterace: 0 x= [1.83333333 1.75       1.28571429]
iterace: 1 x= [1.72619048 1.68452381 1.85714286]
iterace: 2 x= [2.03373016 1.99702381 1.79251701]
iterace: 3 x= [1.89725057 1.88782596 2.01360544]
iterace: 4 x= [2.04419407 2.03249008 1.9239148 ]
iterace: 5 x= [1.95112738 1.95090889 2.02822319]
iterace: 6 x= [2.0304753  2.02632975 1.96502856]
iterace: 7 x= [1.97373769 1.97489545 2.02058363]
iterace: 8 x= [2.01866    2.01685739 1.981572  ]
iterace: 9 x= [1.98516687 1.986121   2.01281354]
iterace: 10 x= [2.0110331  2.01011505 1.98967752]
iterace: 11 x= [1.99146707 1.99208048 2.00761849]
iterace: 12 x= [2.00644908 2.00594248 1.99408031]
iterace: 13 x= [1.99505933 1.99542789 2.00446174]
iterace: 14 x= [2.00375491 2.00346604 1.99657625]
iterace: 15 x= [1.99713278 1.9973494  2.00259954]
iterace: 16 x= [2.00218331 2.00201658 1.99801388]
iterace: 17 x= [1.99833475 1.99846111 2.00151187]
iterace: 18 x= [2.0012689  2.00117225 1.99884664]
iterace: 19 x= [1.99903257 1.99910609 2.00087874]
iterace: 2

### Domácí cvičení

#### DCv.4.1: Lorem